### ISSUE TITLE
custom resource subclass of existing inpec resource no longer works

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#1300] opened 2016-11-18 00:11 UTC
### Description

I’ve got a simple custom profile with a custom library that is a subclass of `JsonConfig` resource:
```
class NodeAttributes <JsonConfig
  name 'node'
  def initialize
    super('/tmp/node.json')
  end
end
```

That used to work, but now I get
```
libraries/node.rb:2:in `load_with_context': uninitialized constant #<Class:#<#<Class:0x007fa05aa40b08>:0x007fa05aa409f0>>::JsonConfig (NameError)
    from /Users/jmiller/.chefdk/gem/ruby/2.3.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:146:in `instance_eval'
    from /Users/jmiller/.chefdk/gem/ruby/2.3.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:146:in `load_with_context'
    from /Users/jmiller/.chefdk/gem/ruby/2.3.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:135:in `load_library_file'
    from /Users/jmiller/.chefdk/gem/ruby/2.3.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:124:in `block in load_libraries'
    from /Users/jmiller/.chefdk/gem/ruby/2.3.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:122:in `each'
    from /Users/jmiller/.chefdk/gem/ruby/2.3.0/gems/inspec-1.4.1/lib/inspec/profile_context.rb:122:in `load_libraries'
```
  
is that expected?

### InSpec and Platform Version

inspec 1.4.1  Mac OSX

### Replication Case

The profile is here: https://github.com/jeremymv2/test-inspec/tree/master/test/integration/profile

**Comment by jeremymv2** [comment] 2016-11-28 16:41
@chris-rock took a little peek into this.  The uninitialized constant error above can be easily fixed by adding `include Inspec::Resources` to the anonymous class that gets created for providing the profile context to be instance_eval'd against, just after this line:  https://github.com/chef/inspec/blob/master/lib/inspec/library_eval_context.rb#L36

However, the next issue is that the `node` object above never gets registered (as verified in pry) and is therefore unavailable in the inspec dsl scope.  It appears that the `Inspec.resource()` method is artificially creating an opportunity for resource registration at compile time that `class NodeAttributes <JsonConfig` doesn't allow for.

**Comment by chris-rock** [comment] 2016-11-28 16:47
Is

```
class NodeAttributes < Inspec::Resources::JsonConfig
  name 'node'
  def initialize
    super('/tmp/node.json')
  end
end
```
working?

**Comment by jeremymv2** [comment] 2016-11-28 16:52
@chris-rock No, but `::Inspec::Resources::JsonConfig` does.  I believe that's due to https://github.com/chef/inspec/blob/master/lib/inspec/library_eval_context.rb#L43  which creates a overlapping namespace so that there is only the `.resource` singleton method available under `Inspec`.

**Comment by jeremymv2** [comment] 2016-11-28 18:47
It looks like in a very basic scenario, when executing a profile with one control file and one library file, when using `Inspec.resource(1)` to create the parent class, `load_with_context` is being called two times: the 1st time `@resource_registry` doesn't contain the new resource, the 2nd time it does have the new resource registered.  In the same scenario, but when using `class NodeAttributes <JsonConfig` `load_with_context` is only being called once and `@resource_registry` does not contain the new resource.

**Comment by iancward** [comment] 2017-04-18 16:05
I'm seeing a similar issue with trying to use an InSpec profile to create a `node` object to store node attributes configs. If I change `Inspec::Resources::JsonConfig` to `::Inspec::Resources::JsonConfig` it gets past the "uninitialized constant" error, but now I get this error:
`undefined local variable or method 'node'`

**Comment by adamleff** [comment] 2017-04-18 16:22
@iancward Could you create a new issue for your request for assistance, and could you create a gist of your full custom resource so we can take a look? thanks!

**Comment by tpmullan** [comment] 2017-04-18 16:34
That sounds like the exact same error.  Why would you create another issue?  Most projects close duplicate issues.  Just to be redundant I am also facing the same issue and opted to just not use a custom resource for now because of the way it is implemented.

**Comment by adamleff** [comment] 2017-04-18 17:02
@tpmullan if it turns out to not be the same error (or at least not the same cause), then we potentially have a single issue that could be tracking more than one problems in the codebase. My initial read on this was that "undefined local variables" and "uninitialized constants" are possible two different problems and may have different resolutions. I feel like we're splitting hairs on "GitHub Issue Management" however. :)

If you all want to continue on this single issue, I'm perfectly fine with that, but as I stated earlier, we're going to need to see a full resource that doesn't currently function as expected so we can troubleshoot and better understand the use case.

**Comment by jeremymv2** [comment] 2017-04-18 17:55
From what @iancward describes, I'm pretty certain it's the same thing, 1st getting "uninitialized constant" because the subclass wasn't being "included" in the right place in the DSL (see: https://github.com/chef/inspec/pull/1355/files#diff-40e74ce294b3e78f93b3079ec77da7ffR38 for fix)  

Then getting "undefined local variable" because the call to superclass isn't implemented to work this way.  Earlier in the year, I tried #1355 but then ran out of time.

At this point in time, custom resource subclasses of existing inpec resources do NOT work when used like this:
```
class YourCustomResource < AnExistingInspecResourceName
```

For everyone running into this issue, you HAVE to use this DSL as in the example [here](https://github.com/chef/inspec/blob/master/examples/profile/libraries/gordon_config.rb#L4):

```
class GordonConfig < Inspec.resource(1)
```

**Comment by tpmullan** [comment] 2017-04-18 18:08
My issue is from `class NodeAttributes < JsonConfig` where an example is given by this issue.  

@adamleff I don't mean to split hairs on issue management I just wanted to point out that it sounds like the same issue.

**Comment by adamleff** [comment] 2017-04-18 18:10
OK, so it's clear that there appears to be an expectation that a custom resource can subclass an existing resource. I'm not sure that's supported behavior, and it's clearly not working. Creating custom resources is totally supported, however. 

I suggest we leave this issue as-is, and someone can troubleshoot this further.

If anyone is having issues subclassing directly from `Inspec.resource(1)`, then I'd suggest that be logged as a separate issue.

**Comment by tpmullan** [comment] 2017-04-18 18:15
In my mind the assumption is that objects oriented program should be supported.  This used to work with inspec, but was broken when the way classes were loaded was changed.  It does not make sense to me to forcefully break the way ruby works by default.

**Comment by adamleff** [comment] 2017-04-18 18:26
@tpmullan we sometimes have to balance "expected Ruby behavior known by many Ruby developers" with "design choices necessary to provide the proper UX to ALL users of InSpec." Sometimes we can do both and sometimes we can't. Not all InSpec users are Ruby engineers.

Let's assume positive intent here in that we don't deliberately or "forcefully break" expected behavior unless we a) made an unintended mistake or b) had a good design reason to do so. That's why I'm suggesting this issue not be closed and instead left open for further investigation. We may come back and say that subclassing core resources is not going to be supported but we'll have a reason for that decision. 

Thank you in advance for your understanding.

**Comment by tpmullan** [comment] 2017-04-18 18:40
@adamleff  I did not mean that to be rude, I just meant that it is a developer based assumption that was not necessarily in the specification anywhere.  But I feel it is a fairly common assumption, but again I am biased as a Ruby developer.  I did not mean to imply that the change was not made for a reason, and those reasons probably add value in different ways to inspec as a whole.  I just wanted to note that it used to work and the way it was changed breaks common design patterns that most developers are taught.  For example the way subclassing works. 

Also the issue is far worse than just subclassing core resources.  No resource can be subclassed.  It must include `class GordonConfig < Inspec.resource(1)`  Now there are ways to mixin common methods, but this just seems like a very cumbersome way to architect a profile.

**Comment by adamleff** [comment] 2017-04-18 18:48
Thank you for your feedback.

**Comment by chris-rock** [comment] 2017-04-19 08:17
Please, let us focus on the technical issues. I did a quick investigation. The following works without any issue as a resource in InSpec Core:
```
module Inspec::Resources
  class MyFile < JsonConfig
    name 'my_file'
    def initialize
      super('/tmp/node.json')
    end
  end
end
```
But as soon as I put this into a profile (without class scoping), it is not working anymore.
```
class MyFile < ::InSpec::Resource::JsonConfig
  name 'my_file'
  def initialize
    super('/tmp/node.json')
  end
end
```
This is a bug in InSpec. You should be able to derive from the built-in resources. I pushed a profile that is not working here: https://github.com/chef/inspec/pull/1674

A workaround is:
```
class MyFile < Inspec.resource(1)
  name 'my_file'
  attr_reader :content
  def initialize
    @content = Hashie::Mash.new(inspec.json('/tmp/node.json').params)
  end
end
```
which allows you to access the data via
```
describe my_file.content do
  its('key') { should eq 'value' }
end
```
Another option is to just use:
```
my_file = json('/tmp/node.json')

describe my_file do
  its('key') { should eq 'value' }
end
```
Then `my_file` can be accessed in multiple areas of the test file. For this solution, an InSpec profile is not required.

My json file was:
```
cat /tmp/node.json 
{ "key": "value" }
```

@tpmullan essentially InSpec resources use our InSpec resource plugin system. Therefore you need to derive from `Inspec.resource(1)`. This is needed to register the new resource. Otherwise the user need to take care of the registration mechanism. This is also very common in other ruby projects like vagrant.

InSpec also implements an isolation mechanism. Therefore two profile can have a resource names `abc` and they will work in their specific context. Otherwise we would get unexpected results if multiple profiles load a resource with the same name (which is Ruby's default behavior).

Nevertheless, I agree that the inheritance of resources should work as expected.

**Comment by miah** [comment] 2019-06-05 21:41
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Closed as completed by miah** 2019-06-05 21:41 UTC
Labels: Type: Bug
