### ISSUE TITLE
Inspec cannot handle password starting with a -

### ISSUE THREAD

**Issue by GavBurke** [inspec/inspec#4420] opened 2019-08-27 13:29 UTC
If the password for the winrm user starts with `-`, the inspec command fails thinking you haven't set a password

# Describe the problem
i.e. running the following
```
inspec exec test-profile --backend winrm --host 10.21.128.67 --port 5986 --user dh-packer-build --password '-r=XQxq%&#%NNs4' --ssl --insecure --self-signed --no-distinct-exit --target-id packer-mswin-f5bfb2d3a0 --show-progress
```

returns with the message `Please provide a value for --password. For example: --password=hello.`

**Comment by mhackethal** [comment] 2019-08-27 15:13
Do you execute inspec from a powershell or cmd? If powershell try to use the following quotation `--password="'---secret---password'"  `

**Comment by GavBurke** [comment] 2019-08-28 07:53
Unfortunately neither, we run it with bash

**Comment by zenspider** [comment] 2019-10-09 23:10
Dupe of #4382.

**Closed as completed by zenspider** 2019-10-09 23:10 UTC
Labels: Platform: Windows, Type: Support
