### ISSUE TITLE
The control.rb object 'to_hash' function is missing `refs`

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#2878] opened 2018-03-25 22:54 UTC
### 🎛 Description
🐛 bug report

see title
https://github.com/chef/inspec/blob/master/lib/inspec/objects/control.rb#L20-L22

### 🌍 InSpec and Platform Version

`master`

**Comment by aaronlippold** [comment] 2018-03-25 22:56
is the fix?

```
def to_hash
  { 
    id: id, 
    title: title, 
    desc: desc, 
    impact: impact, 
    tests: tests.map(&:to_hash), 
    tags: tags.map(&:to_hash), 
    refs: refs.map(&:to_hash), 
  }
end
```

**Comment by chris-rock** [comment] 2018-04-04 09:58
We would need to introduce a new reference object that implement the hash function. I switch this to be a feature request, since it is technically not a bug.

**Comment by miah** [comment] 2019-06-05 22:03
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Closed as completed by miah** 2019-06-05 22:03 UTC
