### ISSUE TITLE
Returning custom resource

### ISSUE THREAD

**Issue by viyew** [inspec/inspec#770] opened 2016-05-25 19:18 UTC
### Description

Is there a way to define a custom resource method that returns another custom resource?

I'm trying to define my own database session resource, similar to [mysql_session resource](https://github.com/chef/inspec/blob/master/lib/resources/mysql_session.rb). Instead of returning an [inspec.command](https://github.com/chef/inspec/blob/23c4bc0a6ec13d8d7232350738641049a47a85f1/lib/resources/command.rb) resource in my query method, I'd like to return a custom resource instead. 

I'm running into the problem where the custom resource to return throws NoMethodErrors or NameErrors.

**Comment by chris-rock** [comment] 2016-05-25 19:20
@viyew just write two resources. Your resource gets registered automatically. You can just use `inspec.myotherresource`

**Comment by viyew** [comment] 2016-05-25 21:22
I'm able to use the custom defined resources in my control files, but not in other resources.

For example, in this resource I want to return:

```
class ResourceToReturn < Inspec.resource(1)
  name 'resource_to_return'
  attr_reader   :xyz
  def initialize()
    @xyz = false
  end
end
```

 through a resource I want to use:

```
class ResourceToUse < Inspec.resource(1)
  name 'resource_to_use'
  attr_reader   :abc
  def initialize
    @abc = false
  end
  def returnResource
    inspec.resource_to_return
  end
end
```

 in this control block:

```
title "Test"
control "test-1" do

    rtu = resource_to_use   

    describe rtu do
        its('abc') { should eq true}
    end 

    describe rtu.returnResource do
        its('xyz') { should eq true}
    end
end
```

 the first describe block works but second describe block wouldn't and throws the NoMethodError. 

This is with inspec v0.22.1

**Comment by chris-rock** [comment] 2016-06-03 16:27
@viyew I can confirm that this is not working as expected. Further investigation is required to find out why this is happening.

**Comment by kekaichinose** [comment] 2019-06-12 01:05
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Closed as completed by kekaichinose** 2019-06-12 01:05 UTC
Labels: Type: Bug
