### ISSUE TITLE
Nested grouping of tests

### ISSUE THREAD

**Issue by megamorf** [inspec/inspec#3503] opened 2018-10-12 11:59 UTC
### Description

🐛 bug report

There are contradicting statements regarding nesting:
* https://github.com/inspec/inspec/blame/7deed13425c299ded99ff6e4095b1e0db969a826/docs/migration.md#L189
* https://github.com/inspec/inspec/blame/eb87fd384d68c1d16b917e842d461e5d70bac4a8/docs/inspec_and_friends.md#L45

Incidentally all I want to know is how to further group tests than just `control > describe > it`. There doesn't seem to be a `context` element in InSpec that other frameworks offer. 

### InSpec and Platform Version

Inspec: 
```
2.3.10
```

OS: 
```
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
```

### Replication Case

```ruby
title 'My Test Suite'

control 'control' do
  describe 'grouping element 1' do
    describe http("https://www.google.com") do
      its('status') { should eq 200 }
    end
    describe http("https://www.bing.com") do
      its('status') { should eq 200 }
    end
  end

  describe 'grouping element 2' do
    describe http("https://www.google.com") do
      its('status') { should eq 200 }
    end
    describe http("https://www.bing.com") do
      its('status') { should eq 200 }
    end
  end
end
```

Returns:

```
raceback (most recent call last):
        25: from /usr/local/bin/inspec:105:in `<main>'
        24: from /usr/local/bin/inspec:105:in `load'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/bin/inspec:12:in `<top (required)>'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/cli.rb:184:in `exec'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:102:in `run'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:95:in `load'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:95:in `each'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:96:in `block in load'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:279:in `register_rule'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:279:in `flat_map'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:279:in `each'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:280:in `block in register_rule'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:272:in `get_check_example'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner.rb:322:in `add_resource'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/runner_rspec.rb:27:in `example_group'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:260:in `block in define_example_group_method'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:387:in `subclass'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:387:in `module_exec'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/rule.rb:281:in `block in with_dsl'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/inspec-2.3.10/lib/inspec/rule.rb:281:in `instance_exec'
         1: from /Users/megamorf/Desktop/nesting.rb:5:in `block (2 levels) in load_with_context'
/opt/inspec/embedded/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:726:in `method_missing': `http` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc). (RSpec::Core::ExampleGroup::WrongScopeError)
```

**Comment by chris-rock** [comment] 2018-10-15 06:17
@megamorf Thank you for your question. InSpec does not support nested describes. In all cases that we have experiences so far, the nested blocks are used to drive the output of the test results. We believe, that the rendering of the tests result should not force you to write tests in a specific way. Therefore, we use a common approach for all controls and do not support nested describe blocks at this point.

In your case,  you can write the test as:

```
control 'control-1' do
  title 'grouping element 1'
  describe http("https://www.google.com") do
    its('status') { should eq 200 }
  end
  describe http("https://www.bing.com") do
    its('status') { should eq 200 }
  end
end

control 'control-1' do
  title 'grouping element 2'
  describe http("https://www.google.com") do
    its('status') { should eq 200 }
  end
  describe http("https://www.bing.com") do
    its('status') { should eq 200 }
  end
end
```

or 
```
control 'control' do
  title 'grouping element 1' 
  describe http("https://www.google.com") do
    its('status') { should eq 200 }
  end
  describe http("https://www.bing.com") do
    its('status') { should eq 200 }
  end
  describe http("https://www.google.com") do
    its('status') { should eq 200 }
  end
  describe http("https://www.bing.com") do
    its('status') { should eq 200 }
  end
end
```

In addition,  we support the `describe.one` that allows you to implement or conditions.

**Comment by megamorf** [comment] 2018-10-15 15:21
@chris-rock Thanks for your quick response 👍 

Your example essentially only groups tests in the test suite's source code but not in its output. So from reading the docs, your input and my testing I can conclude that there's no way to drive the structure of the test output in InSpec, right?

```
▶ inspec exec sampletest.rb --reporter cli

Profile: tests from sampletest.rb (tests from sampletest.rb)
Version: (not specified)
Target:  local://

  ✔  control-1: grouping element 2
     ✔  http GET on https://www.google.com status should eq 200
     ✔  http GET on https://www.bing.com status should eq 200


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 2 successful, 0 failures, 0 skipped
```

Other reporters don't seem to handle different titles in repeatedly used controls:

```json
▶ inspec exec sampletest.rb --reporter json | jq
{
  "platform": {
    "name": "mac_os_x",
    "release": "17.7.0"
  },
  "profiles": [
    {
      "name": "tests from sampletest.rb",
      "sha256": "60044b154219e27008078dd378414a859e676acbfd04331b1cd9c445631ecd6b",
      "title": "tests from sampletest.rb",
      "supports": [],
      "attributes": [],
      "groups": [
        {
          "id": "sampletest.rb",
          "controls": [
            "control-1"
          ]
        }
      ],
      "controls": [
        {
          "id": "control-1",
          "title": "grouping element 2",
          "desc": null,
          "descriptions": [],
          "impact": 0.5,
          "refs": [
            {
              "ref": []
            }
          ],
          "tags": {},
          "code": "control 'control-1' do\n  title 'grouping element 1'\n  describe http(\"https://www.google.com\") do\n    its('status') { should eq 200 }\n  end\n  describe http(\"https://www.bing.com\") do\n    its('status') { should eq 200 }\n  end\nend\n",
          "source_location": {
            "line": 1,
            "ref": "sampletest.rb"
          },
          "results": [
            {
              "status": "passed",
              "code_desc": "http GET on https://www.google.com status should eq 200",
              "run_time": 0.208411,
              "start_time": "2018-10-15T17:11:37+02:00"
            },
            {
              "status": "passed",
              "code_desc": "http GET on https://www.bing.com status should eq 200",
              "run_time": 0.175814,
              "start_time": "2018-10-15T17:11:37+02:00"
            }
          ]
        }
      ]
    }
  ],
  "statistics": {
    "duration": 0.387291
  },
  "version": "2.3.10"
}
```

**Comment by chris-rock** [comment] 2018-10-15 16:07
I think it would be interesting to understand your use case better before providing a definitive answer :-) I am not 100% sure I understand what you are trying to achieve.

**Comment by megamorf** [comment] 2018-10-15 19:03
I have a file that contains many controls:

![image](https://user-images.githubusercontent.com/1732128/46971533-86468e00-d0bc-11e8-8d80-4fed510dd529.png)

And each of the controls has multiple describe blocks with 1 or more `it` entries:

```
control 'region1 INT svc1 API Endpoints' do
  impact 0.8
  title 'Test old and new URL paths'

  base_url = "https://int.domain.tld"
  api_url  = "#{base_url}/api"
  deprecated_svc1_versions = ['1']

  # old
  deprecated_svc1_versions.each do |apiVersion|
    describe http("#{api_url}/v#{apiVersion}/version", method: 'GET') do
      its('status') { should eq 410 }
    end
  end

  describe http("#{api_url}/v1_3/version", method: 'GET') do
    its('status') { should eq 200 }
  end

  # new
  deprecated_svc1_versions.each do |apiVersion|
    describe http("#{api_url}/svc1/v#{apiVersion}/version", method: 'GET') do
      its('status') { should eq 410 }
    end
  end

  describe http("#{api_url}/svc1/v1_3/version", method: 'GET') do
    its('status') { should eq 200 }
  end
end
```

I'd like to group tests results visually by `region AND environment AND service` (currently defined as the first 3 strings in the control name) to make them easier to distinguish from one another.

**Comment by aaronlippold** [comment] 2018-10-15 23:02
I am very interested to see where this lands as I will basically the same challenge to help a team solve next week :) Please keep me in the loop.

**Comment by jerryaldrichiii** [comment] 2018-10-16 18:20
I feel like you could separate them into profiles then have a wrapper profile that executes all of them. 

Depending on the use case, profiles might even be able to reduce duplicated code (example: turning `base_url` into an attribute)

**Comment by zenspider** [comment] 2019-10-09 00:26
Referenced documentation is not contradictory as that is referring to migrating from serverspec and describes a correct migration strategy that does not include nested describes.

Nested describes are not supported at this time, as intended. Closing.

**Closed as completed by zenspider** 2019-10-09 00:26 UTC
Labels: Component: Reporters, Aspect: UI-UX
