### ISSUE TITLE
inspec shell: --depends only supports local profiles

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3821] opened 2019-02-20 20:03 UTC
### 🎛 Description

🙋 feature request

Related: #3411 

I don't often use `shell` with remote repos, but when I went to do it today, I found that inspec shell balked at downloading a remote profile.

### 🌍 InSpec and Platform Version

3.6.4

### 🤔 Replication Case

`inspec shell -t aws// --depends https://github.com/inspec/inspec-aws/archive/master.zip`

### 💁 Possible Solutions

Properly use the fetcher system

### 💻 Stacktrace

```
No file provider for the provided path: https://github.com/inspec/inspec-aws/archive/master.zip
```

**Comment by kekaichinose** [comment] 2019-07-02 00:17
@clintoncwolfe if you don't mind, I'd like to close this out as a duplicate of #3411. I'll go ahead and move #3411 into the backlog as well, but this will help keep things clean. Please re-open if there's something different being conveyed in this issue. Thank you!

**Closed as completed by kekaichinose** 2019-07-02 00:17 UTC
Labels: Component: Fetchers, Component: CLI: shell
