### ISSUE TITLE
Attributes in inspec.yml of an overlay profile does not override attributes values in dependent profile

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#3779] opened 2019-02-05 14:39 UTC
### 🎛 Description
Attributes defined in inspec.yml of an overlay profile **does not** override attribute default values in the dependent profile.

The only way seems to be to use the old style `--attrs attributes.yml`

This is this a 🐛 bug report

The expected behavior is attributes defined in the inspec.yml of the overlay profile will override attrs values without having to use `--attrs`

### 🌍 InSpec and Platform Version
3.x

**Comment by aaronlippold** [comment] 2019-02-05 15:08
Please label as a bug. This will bring up two issues as I can see:

What is the load order and precedence. 

We will either have to set that the order of the listed depends will be last in first our or add a prop to the attribute to be 'overwrite' or 'priority' I think. The second option would be needed if we can't guarantee in what order the 'depends' are loaded or stacked.

I think there is an existing issue where @jerryaldrichiii or @jquick talked about this a bit in terms of precedence I will see if I can track it down.

**Comment by clintoncwolfe** [comment] 2019-02-06 15:55
I think we need to pin down the version in which this appeared - it's likely this was a regression from #3756 , released in v3.4.1

**Comment by clintoncwolfe** [comment] 2019-02-06 16:35
My understanding of the repro:

inspec version is 3.4.1 or greater
Profile W depends on profile B
Profile B contains statements in its control files of the form `attribute('an-attribute', default: 'inline-value')`
Profile W's metadata file, inspec.yml, contains

```attributes:
  - name: an-attribute
    default: value-from-wrapper-metadata
```

Upon execution, the expected value of `attribute('an-attribute')` is `value-from-wrapper-metadata`
Actual value is `inline-value`

**Comment by rx294** [comment] 2019-02-06 23:27
Hey @clintoncwolfe 
In the scenario I tried out both profile W and B and attributes defined inspec.yml like so
profile B
```
  - name: db_name
    description: 'name of the specific DB being evaluated within the MSSQL server'
    type: string
    default: 'value for B'
```

profile W 
```
  - name: db_name
    description: 'name of the specific DB being evaluated within the MSSQL server'
    type: string
    default: 'value for W'
```

and the control files grab the attribs using attribute('an-attribute')....we do not have a default value defined in the controls.

During the exec of Profile W ... attribute('db_name') is expected to return 'value for W'
but, currently its still returning 'value for B'

**Comment by clintoncwolfe** [comment] 2019-02-07 02:56
What happens if you use the YAML key `value` instead of `default`, in both places?

profile B
```
  - name: db_name
    description: 'name of the specific DB being evaluated within the MSSQL server'
    type: string
    value: 'value for B'
```

profile W 
```
  - name: db_name
    description: 'name of the specific DB being evaluated within the MSSQL server'
    type: string
    value: 'value for W'
```

**Comment by rx294** [comment] 2019-02-07 12:25
Hey @clintoncwolfe, just tried it out...same behavior. Attributes values in `profile W` inspec.yml is not used during the run

**Comment by ehbello** [comment] 2019-02-22 12:36
Does anyone know any workaround for this in some version 3.x of InSpec? I'm trying to force some values the child profile attributes from the parent profile, just by avoiding the use of the `--attrs` parameter :thinking:

**Comment by clintoncwolfe** [comment] 2019-02-26 00:38
Not at the moment.  A big part of our current work is overhauling the attributes/inputs system.  We're at 3.6 now, and I'd guess it will be in the next few minor versions, we'll have the inputs system based on plugins - certainly before 4.x.  At that point you can do what you please, as onw could make a plugin that does whatever you like.

I'm also not sure what the specified behavior really is here. At one point we were considering that you had to explicitly name the child profile from the parent profile; that gets us out of deciding what overrides what, since an attribute would then always explicitly be associated with one profile.  

@jquick, do you recall anything from ^^ ?

**Comment by aaronlippold** [comment] 2019-04-12 16:01
I think the expected behavior should be a last in first out unless you specifically scope the input to a particular profile. aka if A -> B -> C an input / attribute called 'input_x'.

if C defines 'input_x' and B and A also define 'input_x' then C's version wins.
if we wanted to use A.input_x or B.input_x we would have to give the ability to scope it

Right now this behavior is respect if you use `--attrs` and pass in a `yaml` file, however, attributes in the `inspec.yml' does not seem to support the `depends` from B -> C if I understand it correctly.

**Comment by clintoncwolfe** [comment] 2019-04-12 17:34
On #3875, we have implemented the explicit naming approach. One of our main goals is to have an inputs system that is easy to reason about, and explicitly naming the profile in which you wish to perform an override is very clear, if less convenient.

**Comment by aaronlippold** [comment] 2019-05-12 19:49
to answer the question about the work around which I missed. If you pass and attributes that yamhill file via ATTRS on the CLI it will respect those values no matter what level or depth of dependency you have.

**Comment by clintoncwolfe** [comment] 2019-05-29 20:37
As this has behavior has been changed in v4+ and the workaround (use an --input-file / --attrs file CLI option) works in v3, I'm going to go ahead and close this.

**Comment by moodwrench** [comment] 2019-05-29 21:14
@clintoncwolfe - I don't see any information in the documentation on using this.   How exactly do I set a input/attribute in a wrapper profile and have it used in a child profile without using cli flags or yml files?

$ chef exec inspec -v
4.3.2

**Comment by aaronlippold** [comment] 2019-05-30 19:15
Once this works in v4 are we going to back port a solution to 3x?

**Comment by clintoncwolfe** [comment] 2019-06-03 16:54
We've dropped the ball a bit on the docs - #3880 would cover that, and you can read what we have so far at https://github.com/inspec/inspec/blob/cw/input-docs/docs/inputs.md . Unfortunately, the answer to your problem is not yet documented in that work in progress.

I would guess that the missing piece is that now you must always explicitly name the profile in which you are performing the override. This is a breaking change, new in version 4:

```
# Wrapper profile inspec.yml
inputs:
- name: the_input
  value: value_from_wrapper
  profile: child  # <---- this line is required in inspec v4+
```

**Comment by clintoncwolfe** [comment] 2019-06-03 17:21
~~Hrm, I'm able to repro the problem, even with the change above, using `include_control`. It does appear to be a bug.~~

No, **I** left off the `profile:` entry in my test example. This does work as intended; if the way this was implemented is painful, let's open a fresh issue as a feature request proposing different ways for it to work.

**Comment by clintoncwolfe** [comment] 2019-06-03 17:23
Re backporting to v3: no, attributes were overhauled extensively in v4, and that's just not practical for v3 to make a matching system.

**Comment by clintoncwolfe** [comment] 2019-06-03 21:26
As mentioned, it does work if you remember to use it as written. I'll try to get the docs in.

**Closed as completed by clintoncwolfe** 2019-06-03 21:26 UTC
Labels: Type: Bug, Component: Loader, Component: Inputs, Aspect: Correctness
