### ISSUE TITLE
Reuse test suites using shared_examples or similar

### ISSUE THREAD

**Issue by willejs** [inspec/inspec#338] opened 2015-12-29 22:02 UTC
Currently im copy pasting code across multiple suites, would it be possible to do shared_examples, or some other method to share code? or use require_relative perhaps?

**Comment by chris-rock** [comment] 2015-12-30 09:37
@willejs Is your use-case reflected in this issue: https://github.com/chef/kitchen-inspec/issues/25 ?

**Comment by willejs** [comment] 2015-12-30 09:58
Ah I dont think so @chris-rock.
I currently am testing a consul cluster, and have 3 nodes each in a suite, i want to run the same tests on these three suites, and not have to copy paste the code. I tried to symlink, relative_require and other tricks with no luck. Any suggestions?

**Comment by chris-rock** [comment] 2015-12-30 10:33
If I got you right, you are targeting production nodes instead of a cluster running via test-kitchen. Are you running inspec locally on each machine?

Why not use our new profile structure: https://github.com/chef/inspec/blob/master/docs/profiles.rst that will be released with the next inspec release. In combination with inspec`s remote functionality, you could test your cluster from your workstation.

**Comment by chris-rock** [comment] 2015-12-30 10:39
You could also use public shared test profiles:
`inspec exec https://github.com/chris-rock/inspec-openstack-security.git`. This will load the tests directly from github at execution time.

**Comment by ceilfors** [comment] 2016-08-18 19:12
I'm looking for something similar in inspec as well to be used in kitchen where I would be able to:
- Reuse a group of resources
- Pass different variables in different test suites to this group of resources

An example in serverspec from elasticsearch cookbook:
- [Defining shared_examples_for](https://github.com/elastic/cookbook-elasticsearch/blob/v2.3.2/test/integration/helpers/serverspec/install_examples.rb#L3)  for reuse in test suites
- [Calling the shared_examples_for](https://github.com/elastic/cookbook-elasticsearch/blob/v2.3.2/test/integration/override_package/serverspec/default_spec.rb#L12) without arguments in test suite 1
- [Calling the shared_examples_for](https://github.com/elastic/cookbook-elasticsearch/blob/v2.3.2/test/integration/package/serverspec/default_spec.rb#L5) with custom arguments to override the default values in test suite 2

Is this something that can be done via inspec in kitchen? Happy to be pointed to a real example.

**Comment by chris-rock** [comment] 2016-08-18 20:10
@ceilfors you can just use an embedded profiles. This will be placed in a cookbook, therefore no extra repo is required. See https://github.com/chef/kitchen-inspec/blob/master/README.md#directory-structure-with-complete-profile as an example. Let me know if this is solving your issue

**Comment by chris-rock** [comment] 2016-08-18 20:12
@ceilfors you can also easily iterate over describe blocks. we use that as well to dest with different parameters https://github.com/chef/inspec/blob/master/lib/bundles/inspec-compliance/test/integration/default/cli.rb#L16

**Comment by ceilfors** [comment] 2016-08-18 21:17
@chris-rock I've looked into the profile usage in kitchen which is the closest one that I'm looking for (not interested in iteration as I have multiple kitchen test suites). The problem is I can't look for ways to customise the profiles by passing variables per test suites just like the example I have given above.

**Comment by chris-rock** [comment] 2016-08-18 21:29
@ceilfors Have a look at https://github.com/chef/inspec/issues/719, we need to add the attributes support into test kitchen. This will allow you to run the same test "profile" with different variables. It will become much easier for you, once we have dependencies and attributes fully backed in. Could you do me a favor and add a ticket in https://github.com/chef/kitchen-inspec?

**Comment by majormoses** [comment] 2018-06-06 15:17
I think `shared_examples` needs to be implemented/supported in inspec see: https://github.com/inspec/inspec/issues/1522#issuecomment-393330869

**Comment by clintoncwolfe** [comment] 2018-07-13 16:13
Closing as duplicate in favor of #1522

**Closed as completed by clintoncwolfe** 2018-07-13 16:13 UTC
