### ISSUE TITLE
Encoding::UndefinedConversionError when using html reporter

### ISSUE THREAD

**Issue by UnitedHaxor** [inspec/inspec#5587] opened 2021-07-02 11:24 UTC
I'm using the PostgreSQL 12 STIG baseline (a50597d) on my Debian machine. When I execute the controls it runs fine, but when I try to generate an html report, it fails with the following error:

Traceback (most recent call last):
        27: from /usr/bin/inspec:259:in `<main>'
        26: from /usr/bin/inspec:259:in `load'
        25: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.38.1/bin/inspec:11:in `<top (required)>'
        24: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.38.1/lib/inspec/base_cli.rb:35:in `start'
        23: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        22: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        21: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        20: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        19: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.38.1/lib/inspec/cli.rb:285:in `exec'
        18: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.38.1/lib/inspec/runner.rb:136:in `run'
        17: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.38.1/lib/inspec/runner.rb:165:in `run_tests'
        16: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.38.1/lib/inspec/runner_rspec.rb:82:in `run'
        15: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
        14: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
        12: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
        11: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:601:in `run'
         7: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:118:in `example_group_started'
         6: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:208:in `notify'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:208:in `each'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:209:in `block in notify'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters/html_formatter.rb:34:in `example_group_started'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters/html_printer.rb:26:in `print_example_group_start'
         1: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters/html_printer.rb:26:in `puts'
/opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters/html_printer.rb:26:in `write': "\\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

I fixed the controls/*.rb files to use only ascii characters (as mentioned in #3375) but it did not help (every file is text/plain; charset=us-ascii).
So I modified the file /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/formatters/html_printer.rb at line 26 to
@output.puts "  <dt id=\"example_group_#{group_id}\" class=\"passed\">#{h(description.dup.force_encoding(Encoding::UTF_8))}</dt>"

which works now.

I'm using Debian 10 with inspec 4.37.30 and I also tried out 4.38.1.

**Comment by clintoncwolfe** [comment] 2021-07-23 02:47
Have you tried the html2 reporter? The html reporter is largely deprecated, as it produces poorly structured output. You may experience better results with the html2 reporter. 

The html reporter is provided by rspec; no development is done on that reporter by the inspec team.

**Comment by clintoncwolfe** [comment] 2021-09-01 03:52
As we cannot reproduce this issue with the maintained html2 reporter, I'm going to close this.

**Closed as completed by clintoncwolfe** 2021-09-01 03:52 UTC
Labels: Component: Reporters
