### ISSUE TITLE
skipped controls are still executed

### ISSUE THREAD

**Issue by mattray** [inspec/inspec#5050] opened 2020-05-27 22:42 UTC
Controls skipped through including a profile and the skipping them are still executed. This is a problem because the reason they were skipped is they take 15 minutes to time out on failure. 

The expected behavior is not to execute them at all and not report them. The good news is they do not report as time outs, as seen in https://github.com/inspec/inspec/issues/4959

https://github.com/mattray/linux-patch-baseline-exceptions-profile/blob/master/controls/skips.rb

Chef 16.1.0 and InSpec 4.18.114

**Comment by james-stocks** [comment] 2020-05-28 08:34
Hi @mattray -

This is a common pitfall in InSpec. Controls are only skipped after InSpec has finished evaluating your source code and finalised the set of `control` and `describe` blocks to execute or skip. 

In this case I believe the `'patches'` control fully evaluates the `each` loop on [line 21](https://github.com/dev-sec/linux-patch-baseline/blob/master/controls/patches.rb#L21)

```
control 'patches' do
  impact 0.3
  title 'All operating system package updates are installed'
  linux_update.updates.each { |update|      # <----- This gets evaluated.
    describe package(update['name']) do
      its('version') { should eq update['version'] }
    end
  }
  only_if { linux_update.updates.length > 0 }
end
```

InSpec has to evaluate `linux_update.updates` during the initial evaluation of the source file; before it can apply skip logic.

Current options here are to move the `each` logic inside a custom resource (this defers its evaluation until actual test execution); or fork the profile and delete the controls you don't want to be evaluated.

EDIT: The `only_if { linux_update.updates.length > 0 }` might also get evaluated unconditionally before skips can be applied.

**Comment by james-stocks** [comment] 2020-05-28 08:34
cc @kekaichinose

**Comment by james-stocks** [comment] 2020-05-28 08:38
See also https://github.com/inspec/inspec/issues/3433

**Comment by clintoncwolfe** [comment] 2021-04-08 00:58
Work on #5327 may help this, if you wish to waive the problematic controls. 
Overall, this issue is a duplicate of #3433, which contains much more discussion - I'm going to close this in favor of that issue.

**Closed as completed by clintoncwolfe** 2021-04-08 00:58 UTC
