### ISSUE TITLE
Resource Packs need to be proper packages with dependency support and the like

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4903] opened 2020-02-10 19:32 UTC
### 🎛 Description

**Choose one:** is this a 🐛 bug report or 🙋 feature request?

Briefly describe the issue and the expected behavior. Also, please be aware of our [Code of Conduct](https://github.com/inspec/inspec/blob/master/CODE_OF_CONDUCT.md).

### 🌍 InSpec and Platform Version

Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

### 🤔 Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

### 💁 Possible Solutions

If you have already ideas how to solve the issue, add them here.

### 💻 Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by clintoncwolfe** [comment] 2020-06-02 15:59
I think what this issue is referring to is gem dependency support. Resource packs already have a dependency mechanism (resource packs are just profiles, and profiles can declare dependencies for other profiles / resource packs in metadata)

**Comment by james-stocks** [comment] 2020-06-03 13:27
This might be a duplicate of https://github.com/inspec/inspec/issues/3637 then.

**Comment by clintoncwolfe** [comment] 2021-04-02 02:18
Duplicate of #3637

**Closed as completed by clintoncwolfe** 2021-04-02 02:18 UTC
