### ISSUE TITLE
http resource: enable_remote_worker should be true by default in InSpec 2.0

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2228] opened 2017-10-09 11:19 UTC
The `http` resource now supports a remote worker via curl, but it is currently opt-in behavior. In InSpec 2.0, this should become the default behavior and the deprecation warnings removed.

**Comment by mattlqx** [comment] 2017-10-26 15:29
On the current 1.42.3 release, I'm still getting the deprecation warning even when I explicitly set `enable_remote_worker: false` on the `http` resource. I'm not sure if this is intended behavior.

**Comment by adamleff** [comment] 2017-10-26 15:31
@mattlqx It is currently intended behavior because we were not planning on allowing a user to force the `http` resource to operate locally when scanning a remote target (since it would be inconsistent with all of our other resources). Is that something you think we need? If so, can you explain a use case so I can better understand?

**Comment by mattlqx** [comment] 2017-10-26 15:37
I have an InSpec profile for a basic smoke test hooked into Workflow. I prefer allowing a local HTTP request on the runner as this allows an end-to-end connection test from outside the application host, even if a bit contrived since it's only being run on my Automate runners. From this, I at least get the benefit of ensuring some basic level of proper network configuration. There may be scenarios where port 22 is open, but the application port is not and I wouldn't know it if the HTTP request was done on the target. Granted I have other monitoring to tell me if an ACL is incorrect and that's mostly only done on initial configuration anyway. Still, I would appreciate some flexibility here.

**Comment by adamleff** [comment] 2017-10-26 15:39
@mattlqx Thanks for that explanation!

I would argue that test belongs in a separate profile that is run separately from your "scan for stuff on the host" profile. That way that profile can be executed in a variety of situations, not just as part of the workflow, and can be decoupled from testing aspects of the host-under-test itself.

**Comment by mattlqx** [comment] 2017-10-26 15:42
I want to re-arrange the test recipe anyway in order to parallelize tests against the deployed hosts. Running an extra profile wouldn't be too bad in that case. Thanks for the suggestion.

**Comment by adamleff** [comment] 2017-10-26 15:44
If you can think of another case where it makes sense to support this behavior, by all means, PLEASE let us know. We will always strive for consistency wherever we can, but it's possible to consider different behavior if the use cases warrant it. I still think a separate profile is the right call, but again, our minds remain open :)

**Comment by jerryaldrichiii** [comment] 2018-03-19 15:40
This has been completed. Closing this issue. :smile:

**Closed as completed by jerryaldrichiii** 2018-03-19 15:40 UTC
Labels: Type: Enhancement
