### ISSUE TITLE
Verify inspec-aws Gem version pinning doesn't break other products

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#2258] opened 2017-10-18 18:29 UTC
In order to proactively prevent issues with #2233 we need to verify that moving the Gem pinning from https://github.com/chef/inspec-aws doesn't break https://github.com/chef/chef

**Comment by clintoncwolfe** [comment] 2017-10-18 19:55
I think you're saying that inspec-aws's Gemfile may declare dependencies that, when we merge into inspec, may cause conflicts with the chef client.  

Which gems are you referring to?

Is this in the context of the audit cookbook?

**Comment by jerryaldrichiii** [comment] 2017-10-18 20:04
@clintoncwolfe it was a topic that came up in standup and yes your description is correct.

We are specifically worried about `aws-sdk` since we currently use that in Chef for things like chef-provisioning.

I do not think this is in the context of the audit cookbok.

**Comment by clintoncwolfe** [comment] 2017-10-18 21:09
We've discovered at least one potential issue. ChefDK 2.3.4 ships with AWS SDK 2.10.45, possibly caused by Omnibus pinning it to `~> 2` in its gemspec - https://github.com/chef/omnibus/blob/master/omnibus.gemspec#L24

**Comment by clintoncwolfe** [comment] 2017-10-19 15:33
re: audit cookbook, my understanding is updated: when the audit cookbook runs, the chef client's audit handler loads the InSpec gem (and dependencies) - which will trigger a conflict.

**Comment by clintoncwolfe** [comment] 2017-10-20 14:01
@jerryaldrichiii can you link in where it is used in chef-provisioning?

**Comment by jerryaldrichiii** [comment] 2017-10-20 17:41
@clintoncwolfe https://github.com/chef/chef-provisioning-aws/blob/master/chef-provisioning-aws.gemspec#L20

**Comment by adamleff** [comment] 2017-12-19 03:20
We have verified this is potentially a problem for InSpec being included in ChefDK. Closing this card and opening a new one to investigate the best way to proceed.

**Closed as completed by adamleff** 2017-12-19 03:20 UTC

**Comment by clintoncwolfe** [comment] 2017-12-19 16:51
To clarify a bit: If inspec-aws were to depend on AWS SDK v3, it would cause a conflict with several products that pin to v2, including chef-dk, omnibus, and chef-provisioning.  We currently do not need to move to v3 (see aborted https://github.com/chef/inspec-aws/issues/108), and so *we do not currently have a conflict*.

When we do move to v3, we'll need to coordinate across product lines.
