### ISSUE TITLE
Output indicates that zero tests were run if --attrs is specified before profile path

### ISSUE THREAD

**Issue by kelvints** [inspec/inspec#1377] opened 2016-12-21 19:31 UTC
### Description

Zero tests are run if --attrs is specified before the profile path argument. If --attrs is specified after the profile path, the tests in the profile are run as expected.

### InSpec and Platform Version

inspec 1.8.0
Debian Wheezy

### Replication Case

Running the profile-attribute profile in the examples directory:

	$ inspec exec profile-attribute --attrs profile-attribute.yml

	Profile: InSpec Profile (profile-attribute)
	Version: 0.1.0
	Target:  local://

	  bob should
		 âœ”  eq "bob"
	  secret should
		 âœ”  eq "secret"

	Test Summary: 2 successful, 0 failures, 0 skipped
	$ inspec exec --attrs profile-attribute.yml profile-attribute

	Test Summary: 0 successful, 0 failures, 0 skipped

**Comment by chris-rock** [comment] 2017-01-02 10:03
@kelvints Tests are executed, but the output is misleading. We should rename the issue to fix the misleading output.

**Comment by kelvints** [comment] 2017-01-03 19:10
I renamed the issue

**Comment by clintoncwolfe** [comment] 2019-06-07 19:11
Duplicate of #3991

**Closed as completed by clintoncwolfe** 2019-06-07 19:11 UTC
Labels: Type: Bug, Component: Inputs
