### ISSUE TITLE
website header content overlays the main navigation

### ISSUE THREAD

**Issue by SalmonKing72** [inspec/inspec#4514] opened 2019-09-25 02:32 UTC
# Describe the problem
* When scrolling on the desktop website, the header content overlays the main navigation
* When clicking the hamburger menu to open the mobile navigation, the header content overlays the navigation preventing it from being used.

## Possible Solution
update the sass to add a lower or negative z-index value for the `header`

**Comment by james-stocks** [comment] 2019-09-25 14:34
Sounds like a duplicate of https://github.com/inspec/inspec/issues/4331

What browser are you using @salmonking72 ? #4331 was for Chrome on Android.

**Comment by SalmonKing72** [comment] 2019-09-25 14:51
@james-stocks The mobile portion of this is probably duplicative of #4331. I saw the issue still occurring on Safari for iOS, also Firefox, Safari, and Chrome Canary on macOS. The z-index update in my PR related to this fixed both the desktop issue I described and the mobile issue described in #4331. 

**Chrome**
![image](https://user-images.githubusercontent.com/6287664/65612212-e65adb00-df81-11e9-8689-ae4b7ea4cbee.png)

**Firefox**
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/6287664/65612408-32a61b00-df82-11e9-8246-3bd898baec50.png">

**Safari**
![image](https://user-images.githubusercontent.com/6287664/65612477-52d5da00-df82-11e9-95a5-198f9fe0c453.png)

**Comment by james-stocks** [comment] 2019-09-27 13:39
I think this was fixed by https://github.com/inspec/inspec/pull/4515 (but I messed up linking the two :) )

**Comment by kekaichinose** [comment] 2019-09-30 19:21
Closed by #4515

**Closed as completed by kekaichinose** 2019-09-30 19:21 UTC
Labels: Type: Bug, Component: Website
