### ISSUE TITLE
report['platform']['name'] is null on AIX 7.2

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#2100] opened 2017-08-25 11:19 UTC
### Description

Got this inspec report from a user scanning an AIX node:

```json
{
  "version": "1.31.1",
...
  "platform": {
    "name": null,
    "release": "7.2"
  },
  "statistics": {
    "duration": 9.915386
  }
}
```

Would it make sense to return a valid string, say `unknown`, for platform.name and platform.release when they cannot be detected?

**Comment by adamleff** [comment] 2017-08-25 11:38
@chris-rock is going to spin up an AIX node to test.

My vote: don't send `unknown` but instead fail to run InSpec and raise an exception. Many resources depend on valid and accurate OS information (name, version, family). If we're generating a report and we don't have proper OS characteristics, I'd prefer we simply fail to run until the OS is properly supported, even if it behaves similarly to an OS we already support.

**Comment by chris-rock** [comment] 2017-08-27 10:34
My first test shows, that this is not a pure inspec issue:
```
inspec detect -t ssh://u0016746@172.29.152.193 --password abc

== Operating System Details

Name:      AIX
Family:    aix
Release:   7.2
Arch:      powerpc

```
Also running a pure inspec report shows no issue:
```
inspec exec examples/profile -t ssh://u0016746@172.29.152.193 --password abc --format json | jq . 
{
  "version": "1.34.3",
  "profiles": [
    {
      "name": "profile",
      "title": "InSpec Example Profile",
      "maintainer": "Chef Software, Inc.",
      "copyright": "Chef Software, Inc.",
      "copyright_email": "support@chef.io",
      "license": "Apache-2.0",
      "summary": "Demonstrates the use of InSpec Compliance Profile",
      "version": "1.0.0",
      ...
      "sha256": "8eed5154c9fa0174067ab475c0ad4a053f772590d129eb324101fe43ef30794d"
    }
  ],
  "platform": {
    "name": "AIX",
    "release": "7.2"
  },
  "statistics": {
    "duration": 0.970362
  }
}
```

**Comment by chris-rock** [comment] 2017-08-27 11:42
I installed chef 13.3.42.1 on AIX 7.2 and audit cookbook and used the latest audit cookbook with:
```
{
  "audit": {
    "reporter": ["json-file"],
    "insecure": "true",
    "profiles": [{
      "name": "ssh",
      "supermarket": "dev-sec/ssh-baseline"
    }],
    "fail_if_not_present": true
  },
  "run_list":[
    "recipe[aix-base-setup]",
    "recipe[audit]"
  ]
}
```

I saw the following result:
```
shd-41","sshd-42","sshd-43","sshd-44","sshd-45","sshd-46","sshd-47","sshd-48"],"id":"controls/sshd_spec.rb"}],"attributes":[],"sha256":"3cd02faf99fcb75aefe3e3932498dbeadb668b056fa4a4c61455a6e920e5a17c"}],"platform":{"name":"AIX","release":"7.2"},"statistics":{"duration":0.743459}}
```

**Comment by chris-rock** [comment] 2017-08-27 11:46
@alexpop I cannot reproduce the issue with Chef 13 + audit and with pure inspec. I tested on AIX 7.2 only

**Comment by adamleff** [comment] 2017-08-28 11:39
I'm going to close this issue for now since it's not reproducible, but if we can get some repro steps added to this issue, I'll immediately reopen it.

**Comment by arlimus** [comment] 2017-09-04 15:55
We received some feedback on this issue, I'm starting to think it's still valid:
```
Uname -s returns 'AIX'
Uname -rvp returns '2 7 powerpc'
```

**Comment by arlimus** [comment] 2017-09-04 15:56
I'm starting to suspect https://github.com/chef/train/blob/master/lib/train/extras/os_detect_unix.rb#L17
(kudos @alexpop for finding it)

**Comment by cattywampus** [comment] 2017-10-03 19:09
I was able to reproduce this error using Inspec v1.19.1, which yields the following output from `inspec detect`

```
== Operating System Details

Name:  
Family:    aix
Release:   7.1
Arch:      powerpc
```

However, after I upgrade to v1.40.0 the `Name:` is filled out properly as `AIX`.

**Comment by adamleff** [comment] 2017-10-03 22:10
Given that feedback, I'm going to close this since we're unable to reproduce with newer InSpec versions. Thanks!

**Closed as completed by adamleff** 2017-10-03 22:10 UTC
Labels: Type: Bug
