### ISSUE TITLE
overhaul skip

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#613] opened 2016-04-05 08:54 UTC
**Problems:**
1. `skip` is used for both errors and intended skips => cannot differentiate between intended and unexpected exceptions
2. `only_if` throws out controls instead of marking them as skipped
3. `only_if` is missing for controls
4. `supports` silently skips all controls
5. **optional** ruby conditionals (`if` / `else`) completely cut off controls from `inspec json` generation; either offer an alternative or rethink if `inspec json` is really needed

**Suggestions:**

**WIP** 
- [x] a) Let `only_if` in file mark controls instead of ignoring their code
- [x] b) Add `only_if` as a keyword for controls
- [x] c) Let `depends` mark controls instead of silently skipping them
- [ ] d) Introduce skip categories
  - Anonymous skips are the foundation
  - `Unsupported` is used for e.g. OS-support, platform, ... (`only_if` would throw this type of skip)
  - `UserError` for e.g. incorrect credentials, sudo permissions, ... (used resources)
  - Use `StandardError` for all unexpected results (see thoughts below)
- [ ] e) Add explicit easy grouping of controls (`control_group` ?); Controls will still have grouping on the file-level (i.e. to write only_if in headers)

**Thoughts:**
- Standard errors are great to handle unexpected results, but they should be more informative if they can. For example:
  
  ``` ruby
  describe file('xyz') do
    its('content') { should eq 'abc' }
  end
  ```
  
  If the file isn't readable, don't just say `nil doesn't equal 'abc'` but instead: `file cannot be read...`
- imho it's ok to use ruby conditionals within `control` blocks to manage tests:
  
  ``` ruby
  control "xyz" do
    ...
    if service('a').enabled?
      describe ...
    else
      describe ...
      describe ...
    end
  ```

**Comment by chris-rock** [comment] 2016-04-05 09:46
#611

**Comment by chris-rock** [comment] 2016-04-05 10:11
I am all in on: a), b) and c)

I see some additional issues with d):
- attributes are missing (UserError? or ArgumentError?)
- dependencies could not be resolved (ExecutionError?)

I would like to handle e) as a separate issue. I get the point that we need some kind of grouping, but this also adds complexity to a compliance profile. Before we decide to take a keyword, I would like to understand the usecase better. Do we group something to apply the same `only_if` conditions to controls? Or do we have other use cases in mind?

**Comment by aaronlippold** [comment] 2016-04-05 14:16
👍

**Comment by harish-swamy** [comment] 2017-06-21 02:19
if service('ntp').running?
  describe command('ntpq -p') do
     its(:stdout) { should match /ntp.ubuntu.com/  }
  end
else ??????????
  end
 
My code running . But the problem is, If service is not running then it showing no tests executed. so i wanted put some error code in else statement ...Could you please let me know that how to write error info in else statement .

**Comment by arlimus** [comment] 2017-06-22 13:33
Timeboxed until July 30th to create an RFC for the skip state. If we don't reach this date for the RFC, we will not ship it in 2.0.

**Comment by adamleff** [comment] 2018-01-11 00:18
With the addition of `FailResource` and `SkipResource` exceptions, we've accomplished a clean way to skip resources in a variety of ways. That combined with other completed issues, a) b) and c) are complete.

I think we need to break d) and e) out into separate feature requests and consider closing this issue.

**Comment by adamleff** [comment] 2018-01-11 21:23
e) declared good enough by way of grouping controls by file with a file-level `only_if`

d) no current use cases for different skip categories, especially with the platforms / supports work

**Closed as completed by adamleff** 2018-01-11 21:23 UTC
Labels: Type: Enhancement
