### ISSUE TITLE
inspec check subcommand does not accept --attrs flag

### ISSUE THREAD

**Issue by mschuchard** [inspec/inspec#2038] opened 2017-07-31 15:13 UTC
### Description

`inspec check` subcommand does not accept `--attrs` flag. This makes unit testing of controls within profiles that have code which relies on attributes impossible for cases where default data is not applicable, and inaccurate for cases which do.

### InSpec and Platform Version

current version according to documentation

### Replication Case

n/a

### Possible Solutions

Adding the option via Thor.

### Stacktrace

n/a

**Comment by chris-rock** [comment] 2017-07-31 17:18
@mschuchard Thank you reporting. I am not sure I understand why `inspec check` would need attribute support. It just verifies that the profile is correct.

**Comment by mschuchard** [comment] 2017-07-31 19:17
It also verifies the code in controls. If the `attribute` method is used in the controls without an appropriate default and the code makes use of the attribute value (which it would do for almost all scenarios), then the `check` fails.

**Comment by chris-rock** [comment] 2017-07-31 21:13
Would'nt the solution then to set sensible defaults? Inspec check is intended to be executed with any arguments. Or is there another solution that you can think of?

**Comment by adamleff** [comment] 2017-07-31 21:30
@mschuchard interesting idea, but at that point, you're testing InSpec's ability to raise Ruby exceptions and your system's ability to pass attributes, rather than exercising policies or doing a proper unit test. I'm interested to learn more about what problem you're trying to solve. Thanks!

**Comment by mschuchard** [comment] 2017-07-31 22:19
In some scenarios, I cannot set defaults. For example, we are supplying attribute data for certain characteristics of a system to compensate for the lack of a `host_inventory` like SpecInfra provides for ServerSpec. I cannot set a reasonable default value for, say, the type of processor on a system. Any attempt to do so would allow the `check` to pass, but cause undesired behavior with `exec`.

**Comment by adamleff** [comment] 2017-08-03 02:41
Thanks for explaining, @mschuchard.

I believe this is outside of the scope of the `inspec check` command which is designed to check profile accuracy. Whether an attribute is supplied or not doesn't speak to the accuracy of the profile  but rather the accuracy of the system or person asking InSpec to execute that profile. I therefore agree with @chris-rock that this is not functionality we should add to the `check` command.

However, I can definitely understand how there might be undesired behavior when you `inspec exec` a profile that relies on an attribute that ends up being `nil` for an attribute for which there is no sensible default. That could definitely cause an outpouring of unfriendly Ruby stacktraces, etc. unless you do some Ruby logic in the profile to raise your own exception if the attribute is missing.

I'm wondering if a potential solution here is providing the ability to mark an attribute as "required" and then provide much more helpful error messaging in the `inspec exec` output if a user attempts to execute a profile without providing a required attribute. Am I getting closer to the root issue here, @mschuchard?

**Comment by mschuchard** [comment] 2017-08-03 12:19
So my assumption was that `inspec check` should be validating the base functionality and behavior of a profile. What is its intended use case?

**Comment by adamleff** [comment] 2017-08-04 13:42
@mschuchard `inspec check` does not validate functionality or behavior but rather proper composure/formatting. It checks things like ensuring the metadata file is correct and is not missing required fields, that specified controls are not missing required fields, Ruby syntax is correct, etc. It does not execute the profile.

At this time, I'm going to close this issue. However, if you think the ability to mark a field as "required" will help you in your efforts, please do log a new issue requesting that functionality! (and of course, if you're up to it, we'd be happy to review a pull request adding that functionality as well)

~Adam

**Closed as completed by adamleff** 2017-08-04 13:42 UTC

**Comment by mschuchard** [comment] 2017-08-04 13:50
Ok, sounds good. Do you have a suggestion for a good way to validate the controls prior to deploying a profile (we already spec test libraries and syntax/style check everything so we just need control unit testing)?

I know we could acceptance test them with test kitchen but just looking for unit at the moment.

**Comment by adamleff** [comment] 2017-08-04 14:04
This was a conversation just had internally at Chef yesterday, as a matter of fact!

Currently, the best practice is to simply run `inspec exec` against an existing host, since it's safe to run InSpec given that its resources do not make changes to the target host. It's hard to test a test framework... With something like Chef, which makes changes to the system in question, testing that the changes were made accordingly makes sense. But statically testing test code is a considerably harder nut to crack.

**Comment by chris-rock** [comment] 2017-08-04 14:22
I propose we add a ticket for that use case: "How to test the tests" :-) and try to drill down each types of tests you potentially wanna do: unit tests, test against different os types etc. I like the thinking...

**Comment by adamleff** [comment] 2017-08-04 14:28
As long as the issue is to start exploring the use cases, then I'm totally fine with that. I'm still concerned we don't exactly understand why we need to "test" other than "testing is good, so we should test." What are we testing for? What issues do we expect or desire to uncover?

I'm afraid that as we start exploring this, we'll find it's a relatively large effort to provide a testing framework (that's not RSpec, obviously) around a testing framework which has a high barrier to entry.

**Comment by chris-rock** [comment] 2017-08-04 14:40
I'd like to start to discuss the use cases not the technical implementation. Then we can see if this is in scope for InSpec or if we recommend another tool for doing so.

**Comment by mschuchard** [comment] 2017-08-04 16:08
@adamleff I just hope to have testing that would uncover issues greater than syntax, but less than acceptance. To go back to my earlier use case, an example would be a bad `attribute` method invocation in a control.

@yarnhoj FYI on this.
