### ISSUE TITLE
--sudo does not appear to elevate privileges when evaluating local systems.

### ISSUE THREAD

**Issue by NickRycar** [inspec/inspec#1279] opened 2016-11-03 21:56 UTC
### Description

Using the inspec CLI to evaluate the contents of a local directory only executable by root fails, even when passing the --sudo and --sudo-password flags.

Same script provides expected results when:
* Run directly as the root user
* Run by the same user, prepended with sudo (as opposed to the provided flags)
* Run over SSH with the --sudo flag (works as expected)

### InSpec and Platform Version

Inspec Version: 1.0.0

Reproduced on:
* MacOS 10.11.6
* Centos 7
* Ubuntu 14.04

### Replication Case

To reproduce, I created a file, tester.rb, with the following contents:

```ruby
control "filetester" do
  impact 1.0
  title "Testing files"
  desc "Ensure they're owned by root"
  describe file('/tmp/foo/bar') do
    its('owner') { should eq 'root' }
  end
  describe file('/tmp/foo/bar') do
    its('group') { should eq 'root'}
  end
end
```

I created /foo/bar as root with 700 permissions.
I created /foo/bar as root with 600 permissions.

I then ran the following command in a few different permutations (see error output below)
`/opt/chefdk/embedded/bin/inspec exec tester.rb`

### Possible Solutions

Unsure, but it looks at least to be limited to local inspec execution. Over SSH, it works exactly as expected.

### Stacktrace

Locally (all OSes) as root, or as privileged user prepended with 'sudo' (working):

```bash
$ sudo /opt/chefdk/embedded/bin/inspec exec tester.rb

Target:  local://

  ✔  filetester: Testing files
     ✔  File /tmp/foo/bar owner should eq "root"
     ✔  File /tmp/foo/bar group should eq "root"


Profile Summary: 1 successful, 0 failures, 0 skipped
```

Locally (all OSes) as privileged user with the --sudo flag (not working):

```bash
$ /opt/chefdk/embedded/bin/inspec exec tester.rb --sudo --sudo-password=test

Target:  local://

  ✖  filetester: Testing files (2 failed)
     ✖  File /tmp/foo/bar owner should eq "root"

     expected: "root"
          got: nil

     (compared using ==)

     ✖  File /tmp/foo/bar group should eq "root"

     expected: "root"
          got: nil

     (compared using ==)



Profile Summary: 0 successful, 1 failures, 0 skipped
```

Remote over SSH as privileged user with --sudo flag (working):

```bash
MYMAC:tmp nrycar$ inspec exec tester.rb -t ssh://admintest@X.X.X.X --password 'test' --sudo-password=test --sudo

Target:  ssh://admintest@54.146.143.225:22

  ✔  filetester: Testing files
     ✔  File /tmp/foo/bar owner should eq "root"
     ✔  File /tmp/foo/bar group should eq "root"


Profile Summary: 1 successful, 0 failures, 0 skipped
```

**Comment by aaronlippold** [comment] 2016-12-07 16:50
+1 @chris-rock @arlimus @alexpop Have we had a chance to look into this one? This was put in by one of the MITRE team folks.

**Comment by rshade** [comment] 2017-04-20 21:48
I am also running into this

**Comment by rshade** [comment] 2017-04-20 21:48
I am also running into this

**Comment by chris-rock** [comment] 2017-04-21 06:02
sudo handling is implemented in https://github.com/chef/train/blob/master/lib/train/extras/command_wrapper.rb and is independent from connection handling. Mmh.

**Comment by chris-rock** [comment] 2017-04-21 06:30
Okay, I adapted the tests a little bit:
```
control "filetester" do
  impact 1.0
  title "Testing files"
  desc "Ensure they're owned by root"
  describe file('/foo/bar') do
    its('owner') { should eq 'root' }
    its('group') { should eq 'root'}
    its('content') { should eq "foobar\n" }
  end
  describe command('cat /foo/bar') do
    its('stdout') { should eq "foobar\n" }
  end
end
```
Results in:
```
Profile: tests from trials/filetester.rb
Version: (not specified)
Target:  local://

  ×  filetester: Testing files (2 failed)
     ✔  File /foo/bar owner should eq "root"
     ×  File /foo/bar group should eq "root"
     
     expected: "root"
          got: "wheel"
     
     (compared using ==)
     
     ×  File /foo/bar content should eq "foobar\n"
     
     expected: "foobar\n"
          got: nil
     
     (compared using ==)
     
     ✔  Command cat /foo/bar stdout should eq "foobar\n"

Profile Summary: 0 successful, 1 failures, 0 skipped
Test Summary: 2 successful, 2 failures, 0 skipped

```

That highlights two things. First, sudo permissions are used for local execution as well. In this specific case the `command` resource is highlighting it. Nevertheless, file handling is done differently in local execution and is not respecting the sudo options for local execution.

**Comment by chris-rock** [comment] 2017-04-21 06:34
Since we use local ruby file handling it is difficult to elevate rights for local execution mid-way. As highlighted already, the solution for now is to run inspec with sudo rights: `$ sudo /opt/chefdk/embedded/bin/inspec exec tester.rb`.

Personally, this also feels like the cleanest solution. We should think about making the sudo arguments attached to remote ssh connections only.

**Comment by rshade** [comment] 2017-04-21 12:55
@chris-rock yes this is my test: 
```
[vagrant@server-centos-73 ~]$ inspec shell --sudo
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  centos
    OS family:  redhat
    OS release: 7.3.1611

inspec> salt=`grep test_user_1 /etc/shadow | awk -F'$' '{ print $3 }'`.strip
grep: /etc/shadow: Permission denied

[vagrant@server-centos-73 ~]$ sudo /opt/chef/embedded/bin/inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: help

You are currently running on:

    OS platform:  centos
    OS family:  redhat
    OS release: 7.3.1611

inspec> salt=`grep test_user_1 /etc/shadow | awk -F'$' '{ print $3 }'`.strip
=> "EbKjRgVQ"
```

**Comment by rshade** [comment] 2017-04-21 12:55
I am trying to run with test-kitchen.

**Comment by rshade** [comment] 2017-04-21 12:56
I have also tried running `sudo grep` and the returns in `command not found`

**Comment by chris-rock** [comment] 2017-04-21 12:57
@rshade Wait, the issue is different for test-kitchen. Sudo need to work fine there?

**Comment by chris-rock** [comment] 2017-04-21 12:58
As explained earlier you need to run `sudo inspec shell` if executed locally

**Comment by rshade** [comment] 2017-04-21 13:01
I am pretty sure kitchen-vagrant just call just calls inspec exec --sudo, so I think the kitchen-vagrant plugin might need to be adapted to use sudo inspec across the ssh handler. I was looking here: https://github.com/chef/inspec/blob/master/lib/resources/shadow.rb#L43, and `inspec.file` seems to be running in an elevated fashion. If I could figure out how that `inspec` is built in ruby I might be able to pass it my own file in an elevated fashion

**Comment by rshade** [comment] 2017-04-21 13:02
inspec shell was just my test to see if the same thing was happening locally and remotely.

**Comment by chris-rock** [comment] 2017-04-21 13:02
@rshade no, kitchen-vagrant uses ssh under the hood and sets the sudo properties. See https://github.com/chef/kitchen-inspec/blob/master/lib/kitchen/verifier/inspec.rb#L203-L204

**Comment by adamleff** [comment] 2017-04-21 17:50
Hello, everyone! With the understanding that:

 * `--sudo` will only be for remote scans (and local scans should do `sudo inspec exec`),
 * #1690 has been opened to warn users about using `--sudo` with local scans,
 * #1689 has been merged with additional documentation, and
 * there were Slack conversions over the past 24 hours with @rshade that solved his particular problem in this area...

... I believe this issue is good to close. I will be closing it but happy to reopen it if needed.

**Closed as completed by adamleff** 2017-04-21 17:50 UTC
