### ISSUE TITLE
http resource: unable to override User-Agent header

### ISSUE THREAD

**Issue by lehn-etracker** [inspec/inspec#2245] opened 2017-10-16 15:07 UTC
### Description

http resource is unable to override User-Agent request header.

### InSpec and Platform Version

* Debian Jessie
* Inspec 1.41

### Replication Case

Try following code with ssh target and you will see, your HTTP-Server will get curl User-Agent and not defined string.

```
  describe http('https://localhost/repository/docker-incoming/v2/',
                enable_remote_worker: true,
                headers: {
                  'User-Agent' => 'Docker'
                },
                ssl_verify: false) do
    its('body') do
      should eq(
        '{"errors":[{"code":"UNAUTHORIZED","message":'\
        '"access to the requested resource is not authorized","detail":null}]}'
      )
    end
    its('status') { should eq 401 }
    its('headers.Server') { should match(%r{Nexus\/\d}) }
  end
```

### Possible Solutions

Idea: Extract User-Agent header and override it by curl option.

**Comment by jerryaldrichiii** [comment] 2018-02-05 07:33
@lehn-etracker thank you for opening this issue. I was unable to reproduce this on InSpec 1.45.13.

I tested by running the following on a remote CentOS 7.1 node:

```
echo 'HTTP/1.1 200 OK\r\n' | sudo nc -l -p 443 --ssl
```

Then running the following InSpec test (I tested with the options inside the `http()` as well):

```ruby
# /tmp/my_test.rb

options = {
  enable_remote_worker: true,
  headers: { 'User-Agent' => 'Docker' },
  ssl_verify: false
}

describe http('https://localhost', options) do
  its('status') { should cmp 200 }
end
```

```
inspec exec -t ssh://vagrant:vagrant@127.0.0.1:2222 /tmp/my_test.rb
```

The test passed and here was the response from the server:

```
[vagrant@localhost ~]$ echo 'HTTP/1.1 200 OK\r\n' | sudo nc -l -p 443 --ssl
GET / HTTP/1.1
Host: localhost
Accept: */*
User-Agent: Docker
```

Given these results, I'm closing this issue for now, but please reopen if this is still causing you problems.

**Closed as completed by jerryaldrichiii** 2018-02-05 07:33 UTC
