### ISSUE TITLE
JSON resource to do remote API calls 

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#2394] opened 2017-12-13 12:29 UTC
I would love to use the JSON resource to test remote API calls over https or http

```
describe json('https://something.web/to/name.json') do
  its('name') { should eq 'hello' }
  its(['meta','creator']) { should eq 'John Doe' }
  its(['array', 1]) { should eq 'one' }
end
```

**Comment by adamleff** [comment] 2017-12-13 19:52
@kmf great use case, I'll log this as a feature request. We'd need to be careful in how we implement because we don't want to reproduce all of the existing `http` resource. Perhaps the `json` resource could be modified to take a built-up `http` resource to use to fetch the content, etc.

In the meantime, I would totally join/stack resources here to get what you need. It should hopefully be pretty easy:

```ruby
describe json(content: http('https://something.web/to/name.json').body) do
  its('name') { should eq 'hello' }
end
```

Since the `json` resource (and those that build off of it, such as the `csv` and `ini` resources) can accept raw content with the `content:` option, we can use the `http` resource to fetch the body and then pass that in as content.

Let me know if that works for you.

**Comment by kmf** [comment] 2017-12-13 20:25
Thanks for your help @adamleff 

How would I use that with a Auth Token?

```
curl -X GET "https://something.web:8080/to/name.json" -H  "accept: application/json" -H  "Authorization: Bearer e973e9e2-0545-4631-bb47-be7f10d56236"
```

**Comment by adamleff** [comment] 2017-12-13 22:49
@kmf you should be able to do that easily with the `http` resource as well. I'm going to break it up into multiple lines to make it easier to read given the potential length of the `http` resource call now.

```ruby
http_request = http('https://something.web:8080/to/name.json',
                    headers: {
                      'Accept' => 'application/json',
                      'Authorization' => 'Bearer e973e9e2-0545-4631-bb47-be7f10d56236'
                    })

describe json(content: http_request.body) do
  its('name') { should eq 'hello' }
end
```

**Comment by clintoncwolfe** [comment] 2018-11-19 17:29
refs #3601

**Comment by nsr99** [comment] 2018-12-24 06:40
I am trying to test Azure Load Balancer with inspec using the API calls. My control file looks like below:

**Control file:**
```
control "file_check" do
    http_request = http('https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/myResourceGroupSLB/providers/Microsoft.Network/loadBalancers/myLoadBalancer/backendAddressPools/myBackendPool?api-version=2018-08-01',
                                    headers: {
                                        'Accept' => 'application/json',
                                        'Authorization' => 'Bearer <my-API-token>'
                                     })
    describe json(content: http_request.body) do
      its('name') { should eq 'hello' }
    end
end
```

**Profile file inspec.yml**
```
name: new_profile
title: Checking compliance of resources
license: Apache-2.0
summary: Inspec test for compliance
version: 1.0
inspec_version: '>= 2.1.81'
depends:
  - name: inspec-azure
    url: https://github.com/inspec/inspec-azure/archive/master.tar.gz
supports:
  - platform: azure
```

When running the test I am getting below error:

 **×  file_check: /home/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/newtest/test/integration/new_profile/controls/basic.rb:13
     ×  Control Source Code Error /home/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/new-test/test/integration/new_profile/controls/basic.rb:13
     undefined method `body' for nil:NilClass**

Seems like nothing is stored in http_request, Can anyone suggest where is the issue?

**Comment by kekaichinose** [comment] 2019-06-12 01:56
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Closed as completed by kekaichinose** 2019-06-12 01:56 UTC
