### ISSUE TITLE
Older Inspec Versions Documentation

### ISSUE THREAD

**Issue by MiteshP0** [inspec/inspec#3528] opened 2018-10-18 17:24 UTC
### 🎛 Description

 🙋 feature request

Need documentation on older inspec versions, as I am upgrading to a different chefDK version that is shipped with a different inspec version, and after some research I have noticed that inspec exec command is returning status code 101 in version 2, but in version 1, it will return 0 even if some tests have been skipped. 

I would like to be forwarded to inspec version 1.5 documentation and inspec version 2.2 documentation so I can figure out what the exit codes for inspec exec in version 1.5 are and what the exit codes for version 2.2 are. 

### 🌍 InSpec and Platform Version

inspec 1.51.21 and inspec 2.2.112 on RHEL 7.

### 🤔 Replication Case

N/A

### 💁 Possible Solutions

Provide older version documentation on main inspec.io website.

### 💻 Stacktrace

N/A

**Comment by jquick** [comment] 2018-10-19 00:37
Hey @MiteshP0. This is a pain point for us and we are looking into versioned docs. For now as you have noticed inspec 1 will return 0/1 accordingly. For inspec 2 we have the following:
```
 If all tests passed (no fails, no skips) exit code 0 is returned. If some tests skipped but none failed, exit code 101 is returned. If at least one test failed, exit code 100 is returned. If inspec failed for any other reason, exit code 1 is returned.
```

You can retain the legacy 0/1 exit if you want by passing in `--no-distinct-exit` on the cli command

**Comment by clintoncwolfe** [comment] 2018-10-19 01:44
Thanks for writing in!  I'm going to close this as a duplicate.

Duplicate of #2860, in general need of versioned docs
Refs #1825, regarding exit codes

**Closed as completed by clintoncwolfe** 2018-10-19 01:44 UTC
Labels: Aspect: Docs
