### ISSUE TITLE
apache_conf parses quotes incorrectly

### ISSUE THREAD

**Issue by Paladin** [inspec/inspec#3334] opened 2018-08-29 16:33 UTC
### 🎛 apache_conf drops the final quotation mark in a Header directive

**Choose one:** 🐛 bug report

### 🌍 InSpec and Platform Version

I'm running inspec shell from inspec 2.2.55 on MacOS 10.13.6 

### 🤔 Replication Case

Start with any valid apache conf file. Add this line to enable HSTS:

Header always set Strict-Transport-Security "max-age=15638400"

Now connect with inspec shell and ask for the "Header" param. You'll get back something like:

```
inspec> apache_conf.params['Header']
=> ["always set Strict-Transport-Security \"max-age=15638400"]
```

Note in the returned value the final quotation mark is not present. It correctly escapes the first one, but not the second. The expected return would be:

```
=> ["always set Strict-Transport-Security \"max-age=15638400\""]
```

### 💻 Stacktrace

There's no stack trace because it doesn't crash, it just doesn't do anything.

**Comment by acondrat** [comment] 2018-09-17 09:27
Hi,

Same issue here. Looks like it was introduced somewhere in 2.2. The workaround for us is to go with 2.1
```
gem 'inspec', '~> 2.1.84'
```

**Comment by clintoncwolfe** [comment] 2018-10-19 02:08
Hrm, this sounds like a regression on #3142

**Comment by zenspider** [comment] 2019-10-08 23:45
Duplicate. Closing.

**Closed as completed by zenspider** 2019-10-08 23:45 UTC
Labels: Type: Bug, Component: Core Resources
