### ISSUE TITLE
Odd Error with inspec shell

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#606] opened 2016-03-31 16:28 UTC
inspec shell
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Sorry, you can't use Pry without Readline or a compatible library.
Possible solutions:
- Rebuild Ruby with Readline support using `--with-readline`
- Use the rb-readline gem, which is a pure-Ruby port of Readline
- Use the pry-coolline gem, a pure-ruby alternative to Readline
  /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- readline (LoadError)
  from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:151:in `lazy_readline'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:6:in`block in class:Default'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:125:in `instance_eval'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:125:in`block (2 levels) in class:Default'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/behavior.rb:54:in `public_send'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/behavior.rb:54:in`method_missing'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/history.rb:19:in `restore_default_behavior'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/history.rb:14:in`initialize'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:33:in `new'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:33:in`history'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:222:in `load_history'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:129:in`initial_session_setup'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:154:in `start'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/core_extensions.rb:43:in`pry'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/shell.rb:18:in `load'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/profile_context.rb:37:in`instance_eval'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/profile_context.rb:37:in `load'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/runner.rb:104:in`add_test_to_context'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/runner.rb:88:in `block in add_content'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/runner.rb:88:in`each'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/runner.rb:88:in `add_content'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/shell.rb:19:in`start'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/lib/inspec/cli.rb:140:in `shell_func'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.16.3/bin/inspec:9:in`<top (required)>'
  from /opt/chef-compliance/embedded/bin/inspec:22:in `load'
  from /opt/chef-compliance/embedded/bin/inspec:22:in`<main>'
  [alippold@cocreate-aaronl compliance-profiles]$

**Comment by aaronlippold** [comment] 2016-03-31 16:32
Doing a 'gem update' to see if that resolves the issue

**Comment by aaronlippold** [comment] 2016-03-31 16:40
Ok. I broke my inspec ... :(

inspec shell
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      winrm-fs (~> 0.3)
      excon (>= 0.38.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Sorry, you can't use Pry without Readline or a compatible library.
Possible solutions:
- Rebuild Ruby with Readline support using `--with-readline`
- Use the rb-readline gem, which is a pure-Ruby port of Readline
- Use the pry-coolline gem, a pure-ruby alternative to Readline
  /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/profile_context.rb:37:in `instance_eval': cannot load such file -- readline (LoadError)
  from /opt/chef-compliance/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:151:in `lazy_readline'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:6:in`block in class:Default'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:125:in `instance_eval'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/default.rb:125:in`block (2 levels) in class:Default'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/behavior.rb:54:in `public_send'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/config/behavior.rb:54:in`method_missing'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/history.rb:19:in `restore_default_behavior'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/history.rb:14:in`initialize'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:33:in `new'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:33:in`history'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:222:in `load_history'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:129:in`initial_session_setup'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/pry_class.rb:154:in `start'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/pry-0.10.3/lib/pry/core_extensions.rb:43:in`pry'
  from (eval):1:in `load'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/profile_context.rb:37:in`instance_eval'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/profile_context.rb:37:in `load'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/runner.rb:104:in`add_test_to_context'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/runner.rb:88:in `block in add_content'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/runner.rb:88:in`each'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/runner.rb:88:in `add_content'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/shell.rb:19:in`start'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/lib/inspec/cli.rb:142:in `shell_func'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /opt/chef-compliance/embedded/lib/ruby/gems/2.2.0/gems/inspec-0.17.0/bin/inspec:9:in`<top (required)>'
  from /opt/chef-compliance/embedded/bin/inspec:22:in `load'
  from /opt/chef-compliance/embedded/bin/inspec:22:in`<main>'
  [root@cocreate-aaronl compliance-profiles]#

**Comment by aaronlippold** [comment] 2016-03-31 16:41
Well my inspec shell anyway. Exec, json, detect, init, etc all seem to work still.

**Comment by chris-rock** [comment] 2016-04-04 12:41
Thanks for reporting @aaronlippold We will investigate that issue!

**Comment by chris-rock** [comment] 2016-04-07 16:35
@aaronlippold could you try the following:

`gem install rb-readline`

Which OS are you using?

**Comment by chris-rock** [comment] 2016-04-11 14:18
@aaronlippold I cannot reproduce your issue. Could you share more details?

**Comment by jerryaldrichiii** [comment] 2017-09-11 19:51
I also cannot reproduce your issue. Given the issue's age I'm going to close it. Please reopen if this is still an issue. Thanks!

**Closed as completed by jerryaldrichiii** 2017-09-11 19:51 UTC
Labels: Type: Bug
