### ISSUE TITLE
auditd_rules not working as expected

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#893] opened 2016-08-09 08:43 UTC
### Description

As reported by @kdshah via gitter:

@chris-rock , trying to test the following control after updating the deprecated method from 'contain_match ' to 'match'. But the control fails, which it should not.

```
describe.one do
auditd_rules.lines.each { |entry|
describe entry do
it {should match /^-a always,exit arch=.* key=time-change syscall=adjtimex,settimeofday/}
end
describe entry do
it {should match /^exit,always watch=\/etc\/passwd perm=wa key=identity/}
end
}
end
```

```
 describe.one do
  auditd_rules.lines.each { |entry|
    describe entry do
      it {should match /^-a always,exit arch=.* key=time-change syscall=adjtimex,settimeofday/}
    end
   describe entry do
      it {should match /^exit,always watch=\/etc\/passwd perm=wa key=identity/}
    end
  }
end
```

The audit rules loaded are:

```
 [kdshah@chef-eval-host controls]$ sudo auditctl -l
-a always,exit -F arch=b64 -S adjtimex,settimeofday -F key=time-change
```

Both the rules are failing. The first rule should pass.
### InSpec and Platform Version

InSpec 0.28.0

**Comment by stevendanna** [comment] 2016-09-27 16:03
It looks like this might be a dup of or related to https://github.com/chef/inspec/issues/710

**Comment by arlimus** [comment] 2018-08-11 00:01
Closing as dupe of #710

**Closed as completed by arlimus** 2018-08-11 00:01 UTC
Labels: Type: Bug
