### ISSUE TITLE
Host resource only using ping to test ports and erroneously reporting them valid.

### ISSUE THREAD

**Issue by strocknar** [inspec/inspec#2153] opened 2017-09-14 19:20 UTC
### Description

When using the "host" resource to attempt to discover whether a target can connect to a remote server on a given port, the test will pass as long as the remote server is 'pingable'

### InSpec and Platform Version

1.25.1

### Replication Case

I was using the the following `test.rb` file to verify that specific ports were reachable from the target on a set of remote hosts:
https://gist.github.com/strocknar/97f3b85556c68e90fa3350bd9cc1a3ef

When I executed this against a `target_server` with debug enabled, I noticed that all tests passed. However, the check was done using `ping -w -c 1` instead of using `nc`
* https://gist.github.com/strocknar/6d1b30c2ec5cfba7cf2f49196e36f699

I then checked the server manually using `nc` and found that certain ports were actually blocked. So I wrote the following `new_check.rb` to verify:
* https://gist.github.com/strocknar/e5a1769b5362cd76805b40405d5f1873

As you can see in the output, two ports were actually not reachable.
* https://gist.github.com/strocknar/db1e48c80525232a9ce9213654f68db5

I also verified that netcat was installed on the target server:

```
user@target_server:~$ dpkg -l | grep -i netcat
ii  netcat-openbsd                     1.105-7ubuntu1                             amd64        TCP/IP swiss army knife
user@target_server:~$ which nc
/bin/nc
```

### Possible Solutions

The usage of netcat could be replaced with `/dev/net/<proto>/<target>/<port>` for use natively, but I'm not sure how much effort that would take.

### Stacktrace

See above gists.

**Comment by adamleff** [comment] 2017-09-14 19:23
@strocknar 1.25.1 is actually quite old. v1.28.0 got a fix that addressed TCP reachability checks on Linux OS machines. Can you please try upgrading and report back your findings?

**Comment by adamleff** [comment] 2017-09-14 19:28
As we discussed in Slack, this is likely caused by the older ChefDK in use so we're going to close this issue for now. Happy to reopen it if needed!

**Closed as completed by adamleff** 2017-09-14 19:28 UTC
