### ISSUE TITLE
Update the rubyzip dependency to allow for 2.x

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#4950] opened 2020-03-10 19:38 UTC
## Detailed Description
Update the rubyzip dependency to allow for 2.x instead of ~> 1.2

## Context
We'd like to consume the latest library in chef and this currently limits the version we can consume and prevents us from getting future security updates.

**Comment by clintoncwolfe** [comment] 2021-04-02 01:34
Duplicate of #5200

**Closed as completed by clintoncwolfe** 2021-04-02 01:34 UTC
