### ISSUE TITLE
Supermarket fetch and git transform cause Intermittent Test Failure

### ISSUE THREAD

**Issue by miah** [inspec/inspec#3990] opened 2019-04-27 00:08 UTC
https://ci.appveyor.com/project/chef/inspec/builds/24133481/job/ccmr6mdl9gmd4254

```
Run options: --seed 56327
# Running:
F......................................................#< CLIXML
...................................................................................
Finished in 723.091634s, 0.1908 runs/s, 0.7316 assertions/s.
  1) Failure:
inspec exec::when using profiles on the supermarket#test_0002_can run supermarket profiles from inspec.yml [C:/projects/inspec/test/functional/inspec_exec_test.rb:360]:
Expected # encoding: UTF-8
"[2019-04-26T20:43:59+00:00] WARN: URL target https://github.com/nathenharvey/tmp_compliance_profile/ transformed to https://github.com/nathenharvey/tmp_compliance_profile/archive/master.tar.gz. Consider using the git fetcher\n" to include # encoding: UTF-8
"Profile Summary: \e[38;5;41m1 successful control\e[0m, \e[38;5;9m1 control failure\e[0m, 0 controls skipped\n".
138 runs, 529 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Functional Tests to C:/projects/inspec/coverage. 6179 / 14045 LOC (43.99%) covered.
```

**Comment by clintoncwolfe** [comment] 2019-04-29 15:38
I believe https://github.com/inspec/inspec/pull/3693 was intended as a fix for this

**Comment by zenspider** [comment] 2019-10-02 21:35
What's the status of this? See #4552 and #4181.

**Closed as completed** 2020-05-26 17:19 UTC
Labels: Type: Bug, Aspect: Testing
