### ISSUE TITLE
Windows: registry_key and its property_value is unable to match when property type is dword and value is in hexadecimal

### ISSUE THREAD

**Issue by tejas-shah** [inspec/inspec#1704] opened 2017-04-25 05:06 UTC
### Description

When I run the following test against a windows host it fails in all possible options.
```
describe registry_key ('HKLM\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server') do 
it { should have_property_value('Enabled', :dword, ffffffff) } 
end
```
Also following fails:
```
describe registry_key ('HKLM\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server') do 
it { should have_property_value('Enabled', :dword, 0xffffffff) } 
end
```

And this also fails:
```
describe registry_key ('HKLM\System\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server') do 
it { should have_property_value('Enabled', :dword, 4294967295) } 
end
```
The above fails even if I specify the value in single/double quotes. 

### InSpec and Platform Version

Inspec version 1.2.0 test executed from Redhat 7.1 against a Windows Server 2012 R2 OS using Winrm.

### Replication Case

Execute the commands mentioned in the description of the issue to replicate the issue.

### Possible Solutions

Unless I could debug the inspec output I could have suggest. There is not sufficient information on how to execute inspec EXEC in debug mode to determine the output from powershell.

### Stacktrace

None.

**Comment by chris-rock** [comment] 2017-04-27 11:55
@tejas-shah Thank your for providing the error cases. Can you please verify that those errors still happen with the latest InSpec version?

**Comment by jerryaldrichiii** [comment] 2018-01-26 00:30
@tejas-shah I was unable to reproduce this issue with InSpec version `1.45.13`.

My test box didn't have the exact key you mentioned but I did test it with the following:

## Chef Recipe
```ruby
registry_key('HKLM\System\Test Path') do
  values [{
    name: 'Test Value',
    type: :dword,
    data: 0xffffff
  }]
end
```

## InSpec Test
```ruby
describe registry_key('HKLM\\System\Test Path') do
  it { should have_property_value('Test Value', :dword, 0xffffff) }
end
```

Given the age of this issue I'm going to close it, but please reopen if this is still causing you trouble.

**Closed as completed by jerryaldrichiii** 2018-01-26 00:30 UTC
Labels: Type: Bug
