### ISSUE TITLE
Develop an inspec test for selinux

### ISSUE THREAD

**Issue by nick-oliver** [inspec/inspec#1496] opened 2017-02-19 17:11 UTC
### Description
Currently there is serverspec test for selinux, however there is no similar test in inspec. This test is described here: 
http://serverspec.org/resource_types.html#selinux

One of the items that we verify in our base provisioning of our linux systems is that selinux is configured in a disabled mode.  Using inspec, this cannot be confirmed.

Please include the stacktrace output or link to a gist of it, if there is one.
```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined local variable or method `selinux' for #<#<Class:0x000000040fe9d0>:0x000000040fe0c0>] on default-centos-67
```

**Comment by chris-rock** [comment] 2017-02-21 09:09
@nick-oliver Thank you for reporting. Is this a duplicate of #534 ?

**Comment by adamleff** [comment] 2017-02-24 22:34
Thanks for submitting this request, @nick-oliver! It does appear (to me, at least) that this is a duplicate of #534 as @chris-rock mentioned. Therefore, I'm going to close this issue as a duplicate and ask that you subscribe to #534 for further updates.

However, if you feel this isn't a duplicate, please reopen the issue or comment here asking us to do so, and I'll be happy to.

Thanks again!

**Closed as completed by adamleff** 2017-02-24 22:34 UTC
