### ISSUE TITLE
Inspec Load Time Performance Uplife

### ISSUE THREAD

**Issue by kevin-j-smith** [inspec/inspec#4604] opened 2019-10-17 13:30 UTC
## Detailed Description
When I want to run one or more specific controls out of a profile AND keep the profile metadata in the results output, I must run like so:
```bash
inspec exec --controls control_1 -- profile_with_many_controls
```

For what ever reason, the single control that I want to run makes Inspec process all controls.  It must run all control logic outside of describe blocks.  Things that are not needed.

***SIDE NOTE*** and what must be a symptom of this loading process is that inputs have scoping issues.  Meaning I can create a constant inside of the control block and reference it from another control...even if it is in a different file.  Another symptom is when I rely on dependent profiles, this same behavior happens.  

Granted, I can run `inspec exec -- profile_with_many_controls/control_1` and get the performance that I expect, that is if my control_1 is not in a single file with multiple control blocks.  But what I now lack is the profile metadata in my results.

In this scenario, the profile metadata comes from the inspec.yml as is normal when running a whole profile.

## Context
Run sub-set of controls from profile and report contains profile's metadata.

## Possible Implementation
? Not sure.  This seems to be a deeply rooted design decision kind of behavior.  What would be nice is to, at minimum, 1) find all files in profile and sub-profiles, 2) list all control names then 3) only load the files that have controls which are slotted to be ran.  This would, if the profile structure is conducive, minimize the load time.

It would be interesting to see more parallelism and threading.  IE Concurrency.  Either multiple ssh processes (the number being configurable), batch processing script or a FIFO pipe.

**Comment by zenspider** [comment] 2019-10-17 20:26
This is essentially related to #3760.

**Comment by zenspider** [comment] 2019-10-17 20:28
I don't understand what you're getting at with the title... can you clarify?

**Comment by clintoncwolfe** [comment] 2020-05-24 05:22
This a duplicate of #2857, so we'll track the issue there. Thanks!

**Closed as completed by clintoncwolfe** 2020-05-24 05:22 UTC
Labels: Type: Enhancement, Aspect: Performance, Aspect: Correctness
