### ISSUE TITLE
Discrepancies between Ohai/Chef and Inspec platform with AmazonLinux

### ISSUE THREAD

**Issue by scalp42** [inspec/inspec#3929] opened 2019-04-09 22:37 UTC
### 🎛 Description

Ohai/Chef and Inspec don't report the platform family in the same way with AmazonLinux.

Chef will report the family as `amazon` and Inspec will report it `redhat`.

### 🌍 InSpec and Platform Version

`3.6.6`

### 🤔 Replication Case

```
chef (14.10.9)> node
 => <Chef::Node:0x1a1ee14 @name="vagrant">
chef (14.10.9)> node['platform']
 => "amazon"
chef (14.10.9)> node['platform_version']
 => "2"
chef (14.10.9)> node['platform_family']
 => "amazon"
```

```
[root@vagrant ~]# inspec shell -c 'os.family'
WARN: Unresolved specs during Gem::Specification.reset:
      bundler (>= 1.10)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
redhat
```

### 💁 Possible Solutions

Probably more of a discussion but it bit us.

Thanks!

**Comment by clintoncwolfe** [comment] 2019-04-11 20:48
That is unfortunately as intended; InSpec does not use ohai for platform detection, and has its own implementation with its own foibles.  

Changing that at this point would break a lot of existing profiles; we'd need to implement the change with a lot of gradual deprecation and backwards compatibility.

**Comment by clintoncwolfe** [comment] 2019-04-11 20:49
This is actually a concern of train, the connection / platofrm detection library; I'm going to close this issue here.

**Closed as completed by clintoncwolfe** 2019-04-11 20:49 UTC
Labels: Component: Train
