### ISSUE TITLE
directory: add globbing

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#107] opened 2015-10-12 13:56 UTC
the resource should cover cases like:

``` ruby
Dir.glob('c:/inetpub/wwwroot/**/*.htm') { |web_file|
  ..
}
```

**Comment by TheLonelyGhost** [comment] 2017-12-14 21:38
This seems to be tied functionally to the result of #2277

**Comment by clintoncwolfe** [comment] 2019-02-21 01:23
Closing as dupe of #709

**Closed as completed by clintoncwolfe** 2019-02-21 01:23 UTC
Labels: Component: Core Resources
