### ISSUE TITLE
InSpec resource host not working for port check

### ISSUE THREAD

**Issue by sbommu** [inspec/inspec#1534] opened 2017-03-03 15:29 UTC
### Description

InSpec host resource is not working as expected. Using host resource to check a particular host is reachable on specific tcp port,  this test is always going success even though the specified port is not listening on the host.  Looks to me it is only checking host is pingable or not but not checking for specified port listening or not on the host.

Here is the code 
describe host('example.com', port: 2222, proto: 'tcp') do
  it { should be_reachable }
end
As per the resource documentation above should fail in case 2222 port not listening on example.com but its going success. 

### InSpec and Platform Version

InSpec version is 1.7.1 and OS is CentOS 7.3
### Replication Case

describe host('example.com', port: 2222, proto: 'tcp') do
  it { should be_reachable }
end

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment] 2017-03-03 16:07
@sbommu thank you for submitting this issue! I believe this is a duplicate of #1439, so I'm going to close this issue as a duplicate. If you feel I am incorrect, please comment here and I'll reopen the issue. Otherwise, I encourage you to subscribe to #1439 for further updates once they become available.

Thank you!

**Closed as completed by adamleff** 2017-03-03 16:07 UTC
