### ISSUE TITLE
Bug with combination of include_controls and require_controls

### ISSUE THREAD

**Issue by voroniys** [inspec/inspec#3091] opened 2018-05-30 14:25 UTC
### 🎛 Description

bug report

Suppose I have basic profile_a. Than I create a profile_b which includes profile_a using include_controls

Now I create profile_c in which I need only small subset of profile_b and profile_a without several check.
So I set:
```
require_controls 'profile_b' do
  control 'A'
  control 'N'
end
include_controls 'profile_a' do
  skip_control 'X'
  skip_control 'Z'
end
```
My expectations that will be executed controls A & N from profile_b and all controls of profile_a, except X & Z
But in the run I've got only A&N from profile_b are executed, but all controls of profile_a are skipped despite my include_controls in profile_c

### 🌍 InSpec and Platform Version

inspec --version
2.1.72

### 🤔 Replication Case

see above

**Comment by jquick** [comment] 2018-05-30 18:20
Thanks for this @voroniys !
Related to https://github.com/inspec/inspec/issues/2950

**Comment by jerryaldrichiii** [comment] 2018-11-30 20:15
I am unable to reproduce this with 3.0.61.

I created a profile_a which has a dependency defined of profile_b. The controls in profile_b look like so:

```ruby
control 'sleep' do
  describe command('sleep 10') do
    its('stdout') { should eq 0 }
  end
end

control 'just_me' do
  describe 'foo' do
    it { should eq 'foo' }
  end
end
```

I've tested both the below in profile_a and it behaved as expected:

```ruby
require_controls 'example' do
  skip_control 'sleep'
  control 'just_me'
end
```

```ruby
include_controls 'example' do
  skip_control 'sleep'
end
```

```ruby
include_controls 'example'

# From CLI
inspec exec profile_a --controls just_me
```

**Comment by zenspider** [comment] 2019-10-07 21:40
No repro. Closing.

**Closed as completed by zenspider** 2019-10-07 21:40 UTC
Labels: Type: Bug, Type: Support
