### ISSUE TITLE
How to handle dotted properties in .properties files.

### ISSUE THREAD

**Issue by g1ps** [inspec/inspec#3595] opened 2018-11-08 13:53 UTC
### 🎛 Description
Relates to: #1330.

More hours, more failure to achieve something basic.

How do I deal with dotted properties in .properties files?

These files are ubiquitous and dotted keys are standard practice, so I'd expect to be able to do this with trivial ease but no luck.

Properties:
````
port.http=1234
someprop=someval
````

Test:
````
  describe parse_config_file('<path>\<file>.properties') do
    its('someprop') { should eq 'someval'}
    its('port.http') { should eq '1234'}
  end
````
Result:
````
     ?  someprop should eq "someval"
     x  port.http
     undefined method `http' for nil:NilClass
````

I've tried:
````
 its(['port', 'http']) { should eq '1234'}
````
but that doesn't work.
````
wrong number of arguments (given 3, expected 1)
````

I've tried using `options` with
````
    multiple_values: false
````
This gets me arrays in return but no values for http. I tried using `ini` on this file in case that would parse the dotted entries, as per its docs. Nope. I can't find a way to escape the dot. Surely this must be possible?

There may be more to `multiple_values` but I have no idea what the doc is trying to tell me or how to work with it:
````
# # file structure:
# key = a
# key = b
# key2 = c
params['key'] = ['a', 'b']
params['key2'] = ['c']
````
or why there isn't a dedicated resource available for such a common file format out of the box. I could, however, see what the output said was being found but it found nothing for the dotted key. I'm stumped again.

### 🌍 InSpec and Platform Version

3.0.12

**Comment by jquick** [comment] 2018-11-08 21:33
This is a known issue and most resources have been updated with array format. For now you can do something like:
```
  describe parse_config_file('test.conf').params['port.http'] do
   it { should eq '1234' }
  end
```
closing this as its a dupe of https://github.com/inspec/inspec/issues/875

**Closed as completed by jquick** 2018-11-08 21:33 UTC

**Comment by g1ps** [comment] 2018-11-09 08:51
Finally! Thanks. Even GitHub's related issue finder didn't find that so I'm not surprised I didn't.
