### ISSUE TITLE
Compliance server actions do not auth correctly with refresh token

### ISSUE THREAD

**Issue by brentm5** [inspec/inspec#1414] opened 2017-01-16 15:19 UTC
### Description

If you login to a compliance server with a refresh token the token will only be valid for the max age before a token expires.  This happens because the login action simply takes the refresh token and generates a token which gets saved with the configuration on disk.

### InSpec and Platform Version

All Versions of inspec

### Replication Case

run the following with valid values `inspec compliance login inspec compliance login <compliance address> --user='<user>' --refresh_token='<refresh_token>'`
Wait an hour or so
Try to run `inspec compliance profiles` or any other command that requires auth to compliance

### Possible Solutions

The solution is to actually implement how the refresh_tokens get used instead of  just using them to generate a token.

**Comment by chris-rock** [comment] 2017-01-17 11:53
Thank you @brentm5 Indeed, this is annoying.

**Comment by jerryaldrichiii** [comment] 2017-09-11 19:53
@brentm5, is this still an issue?

**Comment by clintoncwolfe** [comment] 2019-06-07 19:50
As Compliance is no longer a current product, and the behavior described appears to be as intended, we're going to close this for now.

**Closed as completed by clintoncwolfe** 2019-06-07 19:50 UTC
Labels: Type: Bug, Component: CLI: compliance, Status: Needs Verify
