### ISSUE TITLE
Things should have names

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4127] opened 2019-05-22 22:48 UTC
Inspec uses `Class.new` and `Module.new` with wild abandon. This must stop. It's entirely too difficult to debug any of the internals with all the clever code going on and I don't see a single use-case where these dynamic modules or classes are actually necessary. Use accessors instead of closures.

Aha! Link: https://chef.aha.io/features/SH-2322

**Comment by clintoncwolfe** [comment] 2019-06-13 14:57
Adding search keyword "Anonymous class"

**Comment by clintoncwolfe** [comment] 2021-11-10 03:41
I'm going to close this as a duplicate of #4211

**Closed as completed by clintoncwolfe** 2021-11-10 03:41 UTC
Labels: Aspect: Performance, Type: Tech Debt, Component: Internals
