### ISSUE TITLE
detecting service enabled on Ubuntu 16.04 (systemd)

### ISSUE THREAD

**Issue by unixorn** [inspec/inspec#931] opened 2016-08-17 23:18 UTC
With kitchen 1.10.2 as installed by ChefDK, I'm seeing inspec fail to detect that the apache2 service is running in an Ubuntu 16.04 guest system. The Ubuntu machine is running Chef 12.13.37.

```
describe service('apache2') do
  it { should be_enabled }
end

describe command('systemctl is-enabled apache2') do
  its('exit_status') { should eq 0 }
end
```

Gives the following output:

```
  ✖  Service apache2 should be enabledexpected that `Service apache2` is enabled
  ✔  Command systemctl is-enabled apache2 exit_status should eq 0
```

apache2 is installed and enabled using the following chef recipe excerpt:

```
package 'apache2'

service 'apache2' do
  action :enable
end
```

I suspect that this may be inspec seeing `/etc/init.d/apache2` and not realizing it should be checking systemd for the service status.

**Comment by chris-rock** [comment] 2016-08-18 18:52
which version of inspec is installed on your machine? `gem list | grep 'inspec'`

**Comment by chris-rock** [comment] 2016-08-18 18:52
I assume it is related to https://github.com/chef/inspec/issues/749? Could you update to the latest version of inspec?

**Comment by unixorn** [comment] 2016-08-18 23:50
`/opt/chefdk/embedded/bin/gem list | grep inspec` reports inspec (0.30.0)

**Comment by chris-rock** [comment] 2016-08-19 07:19
Can you share how you have installed apache, so that we can reproduce that full environment?

**Comment by unixorn** [comment] 2016-08-19 17:03
With this snippet:

```
package 'apache2'

service 'apache2' do
  action :enable
end
```

I'm using the stock ubuntu 16 apache2 deb.

**Comment by tas50** [comment] 2016-12-14 01:11
I'm having a similar problem that I think may have the same root cause. I'm installing and enabling nginx on Debian 8, which is systemd based, but the package installs a sys-v script. Inspec correctly detects the service is running, but not that it is enabled for boot. I suspect this is because 'systemctl status nginx' properly returns the status, but 'systemctl is-enabled nginx' fails as the unit file can't be found. /etc/rc2.d/S01nginx is present so the inspec should be detecting it as enabled.

**Comment by stevendanna** [comment] 2016-12-14 08:13
## The original report

The case in the original report works as expected for me:

```
vagrant@vagrant:~$ inspec version
1.4.1
vagrant@vagrant:~$ chef-client -version
Chef: 12.16.42
vagrant@vagrant:~$ cat install_apache.rb
package 'apache2'

service 'apache2' do
  action :enable
end
vagrant@vagrant:~$ cat test_apache.rb
describe service('apache2') do
  it { should be_enabled }
end

describe command('systemctl is-enabled apache2') do
  its('exit_status') { should eq 0 }
end
vagrant@vagrant:~$ sudo chef-client -z install_apache.rb
[2016-12-14T07:56:22+00:00] WARN: No config file found or specified on command line, using command line options.
[2016-12-14T07:56:22+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /home/vagrant.
Starting Chef Client, version 12.16.42
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Installing Cookbook Gems:
Compiling Cookbooks...
[2016-12-14T07:56:24+00:00] WARN: Node vagrant.vm has an empty run list.
Converging 2 resources
Recipe: @recipe_files::/home/vagrant/install_apache.rb
  * apt_package[apache2] action install
    - install version 2.4.18-2ubuntu3.1 of package apache2
  * service[apache2] action enable (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 1/2 resources updated in 08 seconds
vagrant@vagrant:~$ inspec exec test_apache.rb

Target:  local://


  Service apache2
     ✔  should be enabled
  Command systemctl
     ✔  is-enabled apache2 exit_status should eq 0

Test Summary: 2 successful, 0 failures, 0 skipped
```

## @tas50 follow-up
@tas50 what you are describing would be the opposite of the original report wouldn't it?  In the original report, `systemdctl is-enabled` (which inspec uses) was working as expected, whereas in your case `is-enabled` returns incorrect results.

Note, on debian-8 using the latest bento image it looks like the nginx package installs both the systemd config and the sysv config.

That said, I don't doubt we have bugs on Debian 8 because it appears that they are shipping systemd 221 but not the `systemd-sysv-install` shim was introduced in 221 and is required for `is-enabled` to work with sysv-only units.

I have a feeling that we won't get away from these kind of bugs until we move to per-service (rather than just per-platform) level detection of the init type similar to what chef uses (see `Chef::Platform::ServiceHelpers.config_for_service`). 

In the short term, @tas50 can you provide the output of the following:

- `systemctl status nginx.service`
- `systemctl show nginx.service`
- `systemctl is-enabled nginx.service`

I would typically grab this myself, but it is working as expected for me since debian-8 via bento seems to have a systemd-enabled nginx package.

**Comment by tas50** [comment] 2016-12-17 06:37
@stevendanna You're right my bug is actually the reverse. I should have clarified that we're not talking about the nginx package that debian provides. This is the nginx package that nginx.org provides and it does not seem to include a systemd config. I'm modifying our docker config in travis to add systemd-sysv-install so hopefully inspec just magically sees the right thing. I would agree though that the real fix here is going to be some more difficult detection logic because distros and packages are completely inconsistent.

btw: here's the is-enabled failure:

root@79c252d7ed3a:/# systemctl is-enabled nginx.service
Failed to get unit file state for nginx.service: No such file or directory

**Comment by rkgade** [comment] 2017-02-13 11:22
Same issue as the original report but didn't check systemctl .
'service' resource type isn't responding correctly for enabled and running status.

Following Latest Versions. List as follows:
Base OS: Ubuntu 16.04

raj@hydrogen:~/chef-repo/cookbooks/LAMP_Ubuntu
 =>$ chef -v
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 2017-02-13T16:43:41.600391 5794] 2017-02-13T16:43:41.600539 5794] 2017-02-13T16:43:41.600627 5794] 2017-02-13T16:43:41.600703 5794] 2017-02-13T16:43:41.626876 5794] 2017-02-13T16:43:41.627001 5794] 5.6.0
kitchen version: 1.15.0
raj@hydrogen:~/chef-repo/cookbooks/LAMP_Ubuntu
 =>$ gem list | grep inspec
debug_inspector (0.0.2)
inspec (1.11.0)
kitchen-inspec (0.17.0)
raj@hydrogen:~/chef-repo/cookbooks/LAMP_Ubuntu
 =>$

**Comment by damm** [comment] 2017-04-19 02:41
I was writing tests for sensu and kind of ran into a similar problem; systemd is running but the scripts are not really systemd enabled... unfortunately it seems to take the systemd path instead of calling /etc/init.d/sensu-api status

Good issue for reference on this issue.

**Comment by rndmh3ro** [comment] 2017-04-25 06:39
Can confirm the problem on debian8 with systemd, testing with inspec 1.20.0.

**Comment by adamleff** [comment] 2017-04-25 12:11
Hi, friends! Thanks for the conversation and updates on this issue.

I just tried to reproduce the original poster's report and I was unable to:

**ChefDK version**: `1.3.43`
**InSpec version**: `1.19.1`
**Machine**: `bento/ubuntu-16.04`

**Recipe:**
```ruby
package 'apache2'

service 'apache2' do
  action :enable
end
```

**Test:**
```ruby
describe service('apache2') do
  it { should be_enabled }
end

describe command('systemctl is-enabled apache2') do
  its('exit_status') { should eq 0 }
end
```

**Result:**
```
Profile: tests from test/smoke/default
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222


  Service apache2
     ✔  should be enabled
  Command systemctl
     ✔  is-enabled apache2 exit_status should eq 0

Test Summary: 2 successful, 0 failures, 0 skipped
       Finished verifying <default-ubuntu-1604> (0m0.21s).
```

I dropped back to InSpec 1.10.0 and even as far back as 0.30.0 and was unable to reproduce the issue either. :(

@unixorn: as the original reporter, can you provide any other detail to reproduce this issue?

@damm: since you reported this issue most recently, can you please provide a detailed way to reproduce this issue?

@rndmh3ro: The issue with debian8 is the same issue that @tas50 and @stevendanna were discussing above and isn't really InSpec-related, but we could probably do a better job of handling the situation. I'm going to open up a separate issue to track that as it's not quite related to the original issue opened here.

There have been a lot of fixes made to the `service` resource since version 1.10 including more accurate init system detection, so I believe this issue is closed unless we can get someone to help us reproduce it. If it is indeed broken, we'll get it fixed... it's just hard to do so when we can't recreate the issue.

Thank you all!

**Comment by adamleff** [comment] 2017-04-26 19:29
Per the silence here currently as well as some conversations in the Community Slack, I believe this issue is resolved and I'm going to close it now. If it turns out to not be solved, please post here with a way to reproduce it and I'll be happy to reopen the issue. Thank you!

**Closed as completed by adamleff** 2017-04-26 19:29 UTC
