### ISSUE TITLE
Incorrect parsing of windows_task task_to_run name

### ISSUE THREAD

**Issue by johnmccrae** [inspec/inspec#5236] opened 2020-09-01 18:53 UTC
The windows_task resource incorrectly parses the value for a task to be run from inside a scheduled task. 

# Describe the problem
code: 

`its('task_to_run') do
   should cmp "C:\\windows\\system32\\cmd.exe /c 'C:/opscode/chef/bin/chef-client -L C:\\chef/log/client.log -c C:\\chef/client.rb'"
    end`

Notice the placement of the single and double quotes here. 

error:

`     [FAIL]  Windows Task 'chef-client' task_to_run is expected to cmp == "C:\\windows\\system32\\cmd.exe /c 'C:/opscode/chef/bin/chef-client -L C:\\chef/log/client.log -c C:\\chef/client.rb'"

     expected: C:\windows\system32\cmd.exe /c 'C:/opscode/chef/bin/chef-client -L C:\chef/log/client.log -c C:\chef/client.rb'
          got: C:\windows\system32\cmd.exe /c C:/opscode/chef/bin/chef-client -L C:\chef/log/client.log -c C:\chef/client.rb""

     (compared using `cmp` matcher)`

Notice in the error output that the single quotes are dropped and double-quotes are added to the end of the string.

**Comment by kekaichinose** [comment] 2020-09-04 16:26
@johnmccrae thanks for the details of the error. I'll sync with the team next week and prioritize getting this fixed for the next release.

**Comment by Schwad** [comment] 2020-09-07 14:39
I'm just dropping a ping in here to confirm I'm looking into this @johnmccrae 😃 

Thanks!

**Comment by Schwad** [comment] 2020-09-08 09:41
@johnmccrae :

I'm having trouble replicating this on my windows machine, so far all my windows_task parsing is working as expected.

Do you need those single quotes in your expectation?

Can I get the full describe block for this code here so I can see what you're passing to `windows_task` and I should have a better shot at replicating more quickly 👍

**Comment by kekaichinose** [comment] 2020-10-21 15:35
@johnmccrae, apologies but we were not able to reproduce this and have not seen an update on this from your end yet. we'll close this out and revisit if you can provide more details or an updated example. Thanks!

**Closed as completed by kekaichinose** 2020-10-21 15:35 UTC
Labels: Type: Bug, Component: Core Resources

**Comment by johnmccrae** [comment] 2020-10-21 15:58
thanks, it's so weird. I can't repro it now either.
