### ISSUE TITLE
No way to reload the add resources from test code

### ISSUE THREAD

**Issue by coderanger** [inspec/inspec#459] opened 2016-02-17 04:05 UTC
Currently the DSL is baked in to an anonymous module at the start of test execution. This means that if you require a gem that adds new resource types, they aren't visible. This makes packaging custom resources strangely difficult given that it is a defining feature of InSpec.

**Comment by chris-rock** [comment] 2016-02-17 17:33
Duplicate of #353

**Closed as completed** 2016-02-17 17:33 UTC
