### ISSUE TITLE
postgres.rb resource not exposing the 'version' and not finding pg_data/complex pg_data cases and conf_dir when not in standard locations

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1696] opened 2017-04-23 01:44 UTC
### Description

In the current testing I am doing, I have a postgres database has a pg_data dir that is set to a non-standard location and it further separates the configuration by having a separate / individual data directories for each db instance hosted by the RDMS. 

In my case the pattern is: ${PG_DATA}/${DB_NAME} ( "/pgdata/pg-basic" )

This is making it difficult to generalize tests using attributes in the controls.

### Possible Solutions

We could add a new primary case in the resource that first checks to see if we can actively find the pg_data location assuming the postgres process is already started. 

`"ps aux | grep 'postgres *-D' | awk '{print $NF}'"` should give the data_dir in the general case on most unix.  I suggest we perhaps use this as the first pass as trying to find pg_data as I think it will be cross family/platform on the unix/solaris/linux side.

```
[root@411493b19ab0 /]# ps aux | grep 'postgres *-D' | awk '{print $NF}'
/var/lib/pgsql/9.4/data
```

```
bash-4.2$ ps aux | grep 'postgres *-D' | awk '{print $NF}'
/pgdata/pg-basic
```

( I realize that this assumes the postgres process is running but I would say in almost 100% of the cases that this should be a solid assumption given if it isn't most of our tests should fail so we are in trouble anyway )

If this does not produce results we can always fail back to the current code as a fallback rather than the first path. 

This could - in many cases - help us also find the version number more directly as well given that we could also parse the result of this data to find the version number in the pg_data path. 

For example `ps aux | grep 'postgres *-D' | awk '{print $NF}' | rev | cut -d'/' -f 2 | rev`

```
[root@411493b19ab0 /]# ps aux | grep 'postgres *-D' | awk '{print $NF}' | rev | cut -d'/' -f 2 | rev
9.4
```
In my research I also noticed that in the ${PG_DATA} dir there seemed to be a PG_VERSION file. We should find out if this is not a strong standard in PG installs. Perhaps we could also add in a quick line of code to check if that file exists or in the hammer approach, just use a find command to see if PG_VERSION exists on the system.

We may be able to test if ``"ps aux | grep 'postgres *-D' | awk '{print $NF}'"` returns a non null value, if a file called 'PG_VERSION' exists, and its data matches the pattern '#.#' that we have found PG_VER.

I assume we could find a similar command on the windows side.

**Comment by aaronlippold** [comment] 2017-04-23 17:45
I put in a pull request with a quick try at this update : see https://github.com/chef/inspec/pull/1699

**Comment by adamleff** [comment] 2017-04-26 19:03
Someone could be running two postgres instances on the same box, so doing any programmatic detection of where the pg_data directory is could be fragile. The `postgres_conf` resource already accepts a path.

If the issue is that you may potentially not know where that path is, you could use the `command` resource to detect that, or ask your configuration management solution to write out a file somewhere that you could read in that contains the necessary information. But I'm :-1: on modifying the resource to auto-detect non-standard installations.

**Comment by adamleff** [comment] 2017-06-02 20:59
Closing this issue - multiple PRs in flight to address these.

**Closed as completed by adamleff** 2017-06-02 20:59 UTC

**Comment by aaronlippold** [comment] 2017-06-03 01:43
Agreed
