### ISSUE TITLE
sql*plus connection string broken in oracledb_session resource

### ISSUE THREAD

**Issue by jmery** [inspec/inspec#2291] opened 2017-11-07 14:33 UTC
### Description

When using the oracledb_session resource AND `sql` is not available, the connection string used for `sqlplus` is incorrect (missing escaped `"` required for `sqlplus` per Oracle's documentation.

### InSpec and Platform Version

MacOS High Sierra & OEL 7.4
Inspec 1.36.1 & 1.39.1

### Replication Case

1. Pull this docker container: https://store.docker.com/images/oracle-database-enterprise-edition).
2. Create an `env.dat` file with these contents:
```
DB_SID=ORCL
DB_PASSWD=supersecurepass
DB_DOMAIN=localdomain
DB_BUNDLE=basic
```
3. Start the docker container: `docker run -d --env-file ./env.dat -p 1521:1521 -p 5500:5500 -it --name dockerDB --shm-size="8g" store/oracle/database-enterprise:12.2.0.1`
4. `inspec exec <profile> -t docker://<container>`

The profile used for this testing is the to-be-completed `cis-oracledatabase12c-level1-rdbms` profile.

The connection strings can be validated from any client system (but not within the docker container since it does not include the `sql` utility; only `sqlplus`).

### Possible Solutions

See this line:  https://github.com/chef/inspec/blob/c2ec4b95458ab27ecf14289088bbcc4c1fcb1420/lib/resources/oracledb_session.rb#L63

Per Oracle's documentation, `sqlplus` requires double-quotes around the items after the `@` sign in the connection string.  However, we make no distinction between this connection string (i.e. it's the same for `sql` or `sqlplus` as the command binary.

The existing line is correct for `sql`.

For `sqlplus` it should be: `command = "echo \"#{opts}\n#{verify_query(escaped_query)}\nEXIT\" | #{bin} -s #{@user}/#{@password}@\"//#{@host}:#{@port}/#{@service}\""`

There also needs to be a bit of logic added so that this only happens when `sqlplus` is the binary.  There is currently no distinction.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment] 2017-11-07 19:25
Been discussing this in Chef's company Slack with @jmery... I've been unable to reproduce, either at the command line manually or via `inspec shell` and using the resource. sqlplus appears to properly parse the connection string without any additional quotes.

Raw sqlplus:

```
echo "SET MARKUP HTML ON
SET FEEDBACK OFF
SELECT SESSIONTIMEZONE, CURRENT_DATE FROM DUAL;
EXIT" | sqlplus -s SYSTEM/supersecurepass@//localhost:1521/ORCL.localdomain
<p>
<table border='1' width='90%' align='center' summary='Script output'>
<tr>
<th scope="col">
SESSIONTIMEZONE
</th>
<th scope="col">
CURRENT_D
</th>
</tr>
<tr>
<td>
-05:00
</td>
<td>
07-NOV-17
</td>
</tr>
</table>
<p>
```

... and via inspec shell:

```
inspec> sql = oracledb_session(user: 'SYSTEM', password: 'supersecurepass', host: 'localhost', port: 1521, service: 'ORCL.localdomain')
=> Oracle Session
inspec> sql.query('SELECT SESSIONTIMEZONE, CURRENT_DATE FROM DUAL;').row(0).column('SESSIONTIMEZONE').value
=> "-05:00"
```

sqlplus was used because sql was not available:

```
inspec> command('sql').exist?
=> false
```

**Comment by adamleff** [comment] 2017-11-14 03:03
Closing this issue for now @jmery but please reach out, reopen, or ping me if I can help further.

**Closed as completed by adamleff** 2017-11-14 03:03 UTC
