### ISSUE TITLE
Intermittent SSH failures

### ISSUE THREAD

**Issue by myoung34** [inspec/inspec#1666] opened 2017-04-17 13:37 UTC
### Description

I get random (and intermittent) failures that complain about SSH connectivity with  message `Couldn't execute command on SSH.`
My transport options in `.kitchen.yml`: 

```
 12 transport:
 13   username: ec2-user
 14   ssh_key: test.pem
 15   connection_retries: 5
 16   connection_retry_sleep: 2
 17   connection_timeout: 15
```

1. One run (success): 
```
    Finished in 28.27 seconds (files took 3 minutes 18.3 seconds to load)
    67 examples, 0 failures
           Finished verifying <default-amazon> (0m31.22s).
```
2. Random failure by running `kitchen test all` multiple times:
```
           * execute[start amazon-ssm-agent service via upstart] action run
             - execute initctl start amazon-ssm-agent
           # snip output
           System Package amazon-ssm-agent
            should be installed (FAILED - 1)

            Service amazon-ssm-agent
            Couldn't execute command on SSH.

            Failures:

              1) System Package amazon-ssm-agent should be installed
                   Failure/Error: info[:installed] == true

                        NoMethodError:
                               undefined method `[]' for nil:NilClass
```
3. Another but different random failure:
```
         * template[/etc/yum/yum-cron.conf] action create
           - update content in file /etc/yum/yum-cron.conf from 6b6f67 to 11ec03
           --- /etc/yum/yum-cron.conf    2017-03-20 01:32:14.000000000 +0000
           +++ /etc/yum/.chef-yum-cron20170414-2819-1m6sy3w.conf    2017-04-14 12:45:40.055613000 +0000
           @@ -1,84 +1,25 @@
...snip...
File /etc/yum/yum-cron.conf
  should be a file (FAILED - 1)
  content
Couldn't execute command on SSH.

Failures:

  1) File /etc/yum/yum-cron.conf should be a file
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       expected `File /etc/yum/yum-cron.conf.file?` to return true, got false
     # ./test/integration/default/base_spec.rb:22:in `block (2 levels) in load_with_context'

Finished in 43.45 seconds (files took 3 minutes 6.1 seconds to load)
7 examples, 1 failure

Failed examples:

rspec /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.2/lib/inspec/rule.rb[1:1] # File /etc/yum/yum-cron.conf should be a file

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Couldn't execute command on SSH.] on default-amazon
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

### InSpec and Platform Version

kitchen-inspec (latest) with inspec-1.19.2

### Replication Case

Unknown, works  itermittently on AWS EC2 verifier

**Comment by adamleff** [comment] 2017-04-17 15:19
Hi @myoung34 - sorry you're having issues.

I'm unfortunately not able to determine the cause of your problems with the information provided. Can you please run Test Kitchen with debug log enabled (i.e. "kitchen verify foo -l debug"), place the FULL log in a gist, and update this issue with a link? Maybe we'll be able to see some additional helpful information there.

Thanks,
~Adam

**Comment by myoung34** [comment] 2017-04-17 16:44
@adamleff https://gist.github.com/myoung34/1d757514430817e027479babfdec0764

**Comment by myoung34** [comment] 2017-04-20 11:23
@adamleff this is still happening very frequently.

**Comment by adamleff** [comment] 2017-04-21 18:04
@myoung34 sorry I do not have an easy answer for you.

This error:

```
 undefined method `[]' for nil:NilClass
```

... is a bug in InSpec and I'll log a separate issue for that. Why the SSH failure is occurring is a mystery to me and I'm unable to reproduce on my own. I might suggest trying a different AWS region and see if the issue is the network between you and your instance, but I honestly do not have any additional suggestions for you at this time.

**Comment by adamleff** [comment] 2017-06-02 21:15
As there has been no further action on this issue, I'm going to close it. However, I'm more than happy to reopen it if you're able to help us with a reproducible test case. Thanks for using InSpec :)

**Closed as completed by adamleff** 2017-06-02 21:15 UTC
