### ISSUE TITLE
Inspec::Exceptions::ResourceSkipped does not skip for methods inside describe block

### ISSUE THREAD

**Issue by frezbo** [inspec/inspec#4859] opened 2020-01-28 13:28 UTC
Inspec::Exceptions::ResourceSkipped does not skip for methods inside describe block

# Describe the problem

Designed a custom library like this:

```ruby
# frozen_string_literal: true

module Dummy
  class Test
    attr_reader :filter_data

    def initialize(data)
      @filter_data = data
    end

    filter = FilterTable.create
    filter.register_column(:names, field: 'name')
    filter.register_column(
      :tags,
      field: :tags,
      # ref: https://github.com/inspec/inspec/blob/master/docs/dev/filtertable-usage.md#lazy-loading
      lazy: lambda do |row, _criterion, _table|
        tags = row['tags']
        if tags.nil?
          raise(Inspec::Exceptions::ResourceSkipped, '`tags` for resource is missing')
        end

        row[:tags] = tags
      end
    )
    filter.install_filter_methods_on_resource(self, :filter_data)
  end
end

class DummyTest < Inspec.resource(1)
  name 'dummy'

  attr_reader :data

  def initialize(data)
    @data = data
  end

  def ft_valid?
    tags
  end

  private

  def tags
    r_data.tags[0]
  end

  def r_data
    Dummy::Test.new(data)
  end
end

```

now the tests look like this:

```ruby

describe dummy([{'name' => 'foo'}]).valid? do
  it { should eq '' }
end

describe dummy([{'name' => 'foo'}]) do
  its('valid?') { should eq '' }
end

describe dummy([{'name' => 'foo'}]) do
  it { should be_valid }
end
```

Now running these tests product output like this:

```bash
inspec-blueprint (aws:none)(kc:none)(git:RD-2251)*$ inspec exec  /tmp/bp
/Users/ngeorgi/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/rspec-support-3.9.2/lib/rspec/support/differ.rb:133: warning: FilterTable::ExceptionCatcher#respond_to?(:to_ary) uses the deprecated method signature, which takes one parameter
/Users/ngeorgi/work/ruby/inspec/lib/inspec/utils/filter.rb:37: warning: respond_to? is defined here

Profile: InSpec Profile (bp)
Version: 0.1.0
Target:  local://

  #<Class:0x00007fd03c6c7960>::Dummy::Test
     ↺  `tags` for resource is missing
  dummy
     ×  valid? is expected to eq ""
     can't convert FilterTable::ExceptionCatcher to Array (FilterTable::ExceptionCatcher#to_ary gives FilterTable::ExceptionCatcher)
  dummy
     ✔  is expected to be valid

Profile: InSpec Blueprint Profile (inspec-blueprint)
Version: 0.1.1
Target:  local://

     No tests executed.

Test Summary: 1 successful, 1 failure, 1 skipped
```

Screenshot:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/18496730/73267992-1ea84980-4200-11ea-80b6-97bc9186f48e.png">

I expected the second and third test to also be skipped.

**Comment by zenspider** [comment] 2020-02-03 20:06
Yes, this is true and unfortunately by design. This is also a dupe of some number of other issues (#3760 at the very least). Closing.

**Closed as completed by zenspider** 2020-02-03 20:06 UTC

**Comment by frezbo** [comment] 2020-02-04 08:31
@zenspider Thanks for the clarification. Is there any other way to skip a test inside a describe block rather than using `it` and `skip` in the test itself, I would like the resource pack to handle that.
