### ISSUE TITLE
UI: scroll bug on at least one docs page 

### ISSUE THREAD

**Issue by kagarmoe** [inspec/inspec#2433] opened 2018-01-02 18:15 UTC
### Description

Scrolling down the page using the keyboard arrows is impossible; scroll stops and bounces back to top of page. Similar difficult behavior with the mouse.
https://www.inspec.io/docs/reference/cli/

### InSpec and Platform Version

Website

**Comment by adamleff** [comment] 2018-01-02 18:19
I'm unable to reproduce this. Can you let us know browser/version, and perhaps upload a screencast somewhere showing the behavior you're seeing? Can you reproduce this on multiple browsers?

**Comment by kagarmoe** [comment] 2018-01-02 19:15
It is possible that it only happens when the screen is not maximized. Reproduced it in Chrome with browser sized to 50% of the screen, did not happen with browser at 100%. I work with browsers at 50% of the screen much of the time.

**Comment by rollibolly** [comment] 2018-03-28 07:30
Hello. I run into this issue quite often (I have Windows 7, Cef 63.0.3 WPF).
[Please click here](https://drive.google.com/open?id=1O0PtlSnIUs5wMQD7PhVHxag4tYUSGf-l) to watch the video where the scrolling issue can be observed.

**Comment by kekaichinose** [comment] 2019-07-03 00:41
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please reopen the issue and continue the discussion, making sure to provide stack trace or repro data that is relevant to the current version.

Thank you!
__Chef InSpec Team__

**Closed as completed by kekaichinose** 2019-07-03 00:41 UTC
Labels: Type: Bug, Component: Website, Aspect: UI-UX
