### ISSUE TITLE
Incompatible character encodings: UTF-8 and ASCII-8BIT while crawling a page which contains UTF Characters.

### ISSUE THREAD

**Issue by starx** [inspec/inspec#2044] opened 2017-08-02 16:23 UTC
### Description

In a test, trying to verify contents of a web address by crawling is failing. 

>  ------Exception-------
>  Class: Kitchen::ActionFailed
>  Message: 1 actions failed.
>      Failed to complete #verify action: [incompatible character encodings: UTF-8 and ASCII-8BIT] on default-ubuntu-1604
> 

[Kitchen Log](https://pastebin.com/k36mGEY7)

### InSpec and Platform Version

Inspec: 1.31.1
Kitchen: 1.16.0

### Replication Case

A simple test case like this is enough. The page it is crawling should have Unicode characters.

```
describe command 'curl http://test.com' do
  its('stdout') { should match(/test_match/) }
end
```

**Comment by chris-rock** [comment] 2017-08-28 07:56
@starx Are you sure this is happening with every page? I just tested it with `google.com`:
```
describe command 'curl http://google.com' do
  its('stdout') { should match(/test_match/) }
end
```
and got the following output:
```
b inspec exec http.rb 

Profile: tests from http.rb
Version: (not specified)
Target:  local://


  Command curl
     ∅  http://google.com stdout should match /test_match/
     expected "<HTML><HEAD><meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<TITLE>302 Moved...HREF=\"http://www.google.de/?gfe_rd=cr&amp;ei=isujWcG6DKTPXqmgpCA\">here</A>.\r\n</BODY></HTML>\r\n" to match /test_match/
     Diff:
     @@ -1,2 +1,7 @@
     -/test_match/
     +<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
     +<TITLE>302 Moved</TITLE></HEAD><BODY>
     +<H1>302 Moved</H1>
     +The document has moved
     +<A HREF="http://www.google.de/?gfe_rd=cr&amp;ei=isujWcG6DKTPXqmgpCA">here</A>.
     +</BODY></HTML>
     

Test Summary: 0 successful, 1 failure, 0 skipped
```

This error also feels like the ruby/inspec file itself was stored in a wrong charset. Can you ensure your editor stores it in utf-8?

**Comment by starx** [comment] 2017-08-28 16:29
@chris-rock Hi yes, Google works for me too, try a page which has UTF8 characters, not just the encoding. Try my blog http://blog.mrnepal.com

**Comment by adamleff** [comment] 2017-09-05 21:58
I have been able to successfully reproduce this using Test Kitchen / kitchen-inspec. I could not reproduce it using InSpec directly however. I do not believe this is an issue with InSpec core itself.

@starx I'm not 100% sure if this is an issue with Test Kitchen core or with the kitchen-inspec verifier. I'd start with `kitchen-inspec` - could you please open an issue on that repo with your findings? Feel free to refer to this issue in your new issue so we don't lose context. 

I'm going to close this issue since this does not appear to be an issue with InSpec itself at this time.

Thanks!

**Comment by chris-rock** [comment] 2018-09-10 12:02
I can confirm the issue is located in InSpec.

**Closed as completed** 2018-09-10 18:37 UTC
