### ISSUE TITLE
mssql_session fails to pass target credentials as default values

### ISSUE THREAD

**Issue by reddeppas** [inspec/inspec#3177] opened 2018-06-27 12:28 UTC
### 🎛 Description

this a 🐛 bug report 

Briefly describe the issue and the expected behavior
As part of MSSQL Bare metal Servers Validation . 

And also making MSSQL db validation using windows authentication . But it is failing with error , though i am using AD account and i am able connect to the windows servers using inspec detect command .

### 🌍 InSpec and Platform Version
2.2.20
Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using
Windows 2012 R2, BM Servers

### 💻 Stacktrace

For Establishing MSSQL Session using windows authentication:
Could not execute the sql query Msg 18456, Level 14, State 1, Server SC22ONBSQLCL1, Line 1
Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.

EDIT (@clintoncwolfe): Edited to reflect splitting the ticket; only MSSQL auth stuff remains.

**Comment by reddeppas** [comment] 2018-06-29 14:15
Can you please help us what these errors indicates ?

**Comment by clintoncwolfe** [comment] 2018-07-02 14:48
Hi @reddeppas , 
  You're reporting two distinct problems, so I've split the ticket.  The "unable to run validation" issue is being handled on https://github.com/inspec/train/issues/319 .

I'll edit this ticket to reflect narrowing the scope to your MSSQL auth problem.

**Comment by clintoncwolfe** [comment] 2018-07-02 14:54
@reddeppas , some questions would help diagnose the MSSQL auth problem:

1.  Do you expect to be able to login to your MSSQL database as an anonymous user?
2.  Are you able to login to the MSSQL database manually (outside of inspec)?
3.  Could you show us the InSpec control code you are using (be sure to obscure any passwords)?

**Comment by reddeppas** [comment] 2018-07-02 19:18
_Do you expect to be able to login to your MSSQL database as an anonymous user?_
I am running inspec from Linux server and validating remote MSSQL server . Using AD account with windows authentication provided by inspec.
_Are you able to login to the MSSQL database manually (outside of inspec)?_
Yes i am able to test  Authentication using SQL Server DB accounts and AD account is throwing error though() . Do we need to have some special permissions on  AD level to connect from Linux server to MSSQL server using windows authentication .? 
_Could you show us the InSpec control code you are using (be sure to obscure any passwords)?_

```
control 'mssql_sqlqueries-1.0' do
  title 'mssql_sqlqueries'
  desc 'mssql_sqlqueries_checks'
  tag 'MSSQL
  sql = mssql_session(host: instancename) 
  describe sql.query('select name,collation_name from sys.databases').row(0).column('collation_name') do
    its('value') { should eq 'Latin1_General_CI_AS_KS_WS' }
  end
end
```

EDIT (@clintoncwolfe): italics on questions, place code in block

**Comment by clintoncwolfe** [comment] 2018-07-05 20:37
OK, revisiting my first question: do you expect to be able to log into your database server using anonymous credentials (not using inspec), from a remote host? That would be surprising to me if the answer is yes; that would appear to be an unusually insecure setup.

I see here (`mssql_session(host: instancename)`) that you are not providing a username or password. As you mention, and as [the docs](https://www.inspec.io/docs/reference/resources/mssql_session/) say, `mssql_session` will then default to using the credentials that Inspec is using to connect to the machine.

So, what credentials are you using to connect?  If it's anonymous (or not provided), then Inspec is working as intended, and MSSQL is (properly) preventing an anonymous remote user from accessing the database.  I'd suggest making a service account, granting the new account permission to access the database, and then use those credentials with Inspec.

If you're already using a service account with proper permissions, but `mssql_session` thinks you are trying to use ANONYMOUS, then we've found a bug in `mssql_session`.  If you beleive that's the case, please comment with the CLI invocation you are using to run inspec (be sure to obscure any password or hostname).

**Comment by reddeppas** [comment] 2018-07-06 07:08
I am using service account . Below is the Inspec CLI command
inspec shell -t --backend winrm --user 'domain\serviceaccount' --password 'xxxxx' --host ipaddress

In the control file:
sql = mssql_session(host: 'instancename')

**Comment by clintoncwolfe** [comment] 2018-07-06 15:48
Thanks for your patience on this as we get to the diagnosis.  I do believe we've found a bug.

**Comment by reddeppas** [comment] 2018-07-10 13:42
Thanks for the confirmation. Can you please let us know when this will be fixed and released ,

**Comment by clintoncwolfe** [comment] 2018-07-10 15:50
We have a lot of higher priorities at the moment, so it is unlikely the InSpec team will address this anytime soon.  As InSpec is an open source project, any member of the community may contribute a fix, if they are needing something soon.

Also, there is a workaround: you can provide authentication credentials to `mssql_session`.

You could do this (but don't):
```
 sql = mssql_session(host: instancename, username: 'myservice_user', password: 'mypassword') 
```

That's dangerous because you might put your password in your version control, where it will live forever.

Instead, consider using [InSpec attributes](https://www.inspec.io/docs/reference/profiles/#profile-attributes):
```
thepassword = attribute('mssql_password', description: 'Password for the MSSQL service user')
 sql = mssql_session(host: instancename, username: 'myservice_user', password: thepassword) 
```
And in secrets.yaml (which you exclude from source control):
```
mssql_password: supersecret
```

**Comment by Nik08** [comment] 2021-09-17 13:04
This issue is not reproducible anymore, seems like it has been resolved.

Tried this in a control:
```
sql = mssql_session(instance: INSTANCENAME)
describe sql.query("SELECT name, CAST(value as int) as value_configured, CAST(value_in_use as int) as value_in_use FROM sys.configurations WHERE name = 'Ad Hoc Distributed Queries'").row(0).column('Name') do
  its('value') { should eq 'Ad Hoc Distributed Queries' }
end

```
which was executed with the command as mentioned above in this thread, `inspec shell -t --backend winrm --user 'domain\serviceaccount' --password 'xxxxx' --host ipaddress`

And since this seems to be working all fine, closing this.

**Closed as completed by Nik08** 2021-09-17 13:04 UTC
Labels: Type: Bug, Platform: Windows, Component: Core Resources, Component: Train, Platform: Databases
