### ISSUE TITLE
attributes.yml file values vs attribute values in .rb files

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1759] opened 2017-05-04 01:51 UTC
### Description

I have noticed that the values in my attributes.yml file are not overriding the values of my attributes in the source controls files when I am using inspec-kitchen. I have not validated this on the command line yet but have we documented and validated the order of precedence - which values are supported to win?

**Comment by adamleff** [comment] 2017-05-04 11:39
I'm not following, @aaronlippold. Can you give a specific example with both your attributes.yml and your .kitchen.yml files, with the appropriate values redacted if necessary?

**Comment by aaronlippold** [comment] 2017-05-08 14:42
@adamleff I believe the expected behavior if I pass inspec an --attrib=attribute.yml file that the values in the attributes.yml file will override those in the attribute definition of the control_spec.rb file correct.

control_spec.rb in the `controls` directory

```
PG_DBA = attribute(
   'pg_dba',
   description: 'The postgres DBA user to access the database',
   default: 'stig_dba')
``` 

attributes.yml in the `profile` tree

```
pg_dba: 'stig_dba_1'
pg_dba_password: 'testtest' 
```

control_spec.rb - the value of PG_DBA should be 'stig_dba_1' however, it is 'stig_dba' even if I pass in the attributes file it seems.
```
  describe command("PGPASSWORD='#{PG_DBA_PASSWORD}' psql -U #{PG_DBA} -d #{PG_DB} -h #{PG_HOST} -A -t -c \"SHOW log_file_mode\"") do
        its('stdout.strip') { should eq '0600' }
      end
```

**Comment by clintoncwolfe** [comment] 2018-07-05 23:33
The intended behavior is for values in the YAML file to take precedence; the `default` parameter to `attribute()` is only used when either no `--attrs` CLI option is used, or no top-level YAML key with the attribute's name is provided.  

It appears that kitchen-inspec [does support passing InSpec attributes](https://github.com/inspec/kitchen-inspec#use-attributes-with-your-inspec-profiles) to the verifier.  Note that this occurs in the `verifier` section of your `.kitchen.yml`; kitchen also has a key named `attributes` for passing attributes to Chef runs.

If the `.kitchen.yml` were malformed, you'd see the symptom you describe: since kitchen would not be sending any attributes to InSpec, `attribute()` would use the value from the `default` parameter.

If you're sure your .kitchen.yml is correct, let's move this ticket over to [inspec/kitchen-inspec](https://github.com/inspec/kitchen-inspec).  Thanks Aaron!

**Comment by clintoncwolfe** [comment] 2018-11-14 03:18
This has been somewhat answered, and has sat for a bit.  I'm going to close this, but feel free to re-open it if you have more to discuss on this topic.

**Closed as completed by clintoncwolfe** 2018-11-14 03:18 UTC
Labels: Aspect: Integration, Component: Inputs, Type: Support
