### ISSUE TITLE
inspec exec or kitchen verify is not working with un/pw for SSH

### ISSUE THREAD

**Issue by lilmansplace** [inspec/inspec#1970] opened 2017-06-26 15:07 UTC
### Description
I can't get inspec to work with SSH username and password.
It works with SSH keypairs but not with username and password.

### InSpec and Platform Version

```
$ chef -v
Chef Development Kit Version: 1.5.0
chef-client version: 12.21.2
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```

macOS Sierra - 10.12.5

### Replication Case

When attempting to run:
```
$ kitchen verify author-B50
-----> Starting Kitchen (v1.16.0)
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
-----> Verifying <author-B50>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Client error, can't connect to 'ssh' backend: You must configure at least one authentication method for SSH: Agent, Key or Password.] on author-B50
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

or run:
```
$ inspec exec test/integration/default/createcrxuser_spec.rb -t ssh://52.173.191.244 --user='demo' –-password='demo@demo123'
Client error, can't connect to 'ssh' backend: You must configure at least one authentication method for SSH: Agent, Key or Password.
```

yet I can run:
```
$ sshpass -p'demo@demo123' ssh demo@52.173.191.244
Last login: Mon Jun 26 14:42:11 2017 from 192.150.9.200
[demo@kitchen-b50 ~]$
```

**Comment by adamleff** [comment] 2017-06-27 21:21
@lilmansplace thanks for submitting this issue.

Unfortunately, I was not able to reproduce this issue. These are the steps I took:

 * set up a brand new Vagrant box using the `bento/ubuntu-16.04` image
 * logged in, created a new user named `demo` and password `demo@demo123` to match yours, just to be on the safe side
 * Created a standalone test file, named `test_spec.rb` which contains the following test:

```ruby
describe directory('/tmp') do
  it { should be_directory }
end
```

 * Ran the following command and received the following output:

```bash
$ inspec exec ./test_spec.rb -t ssh://127.0.0.1:2222 --user=demo --password='demo@demo123'

Profile: tests from ./test_spec.rb
Version: (not specified)
Target:  ssh://demo@127.0.0.1:2222


  File /tmp
     ✔  should be directory

Test Summary: 1 successful, 0 failures, 0 skipped
 ```

As you can see, it was successful. Can you provide any addition information about your environment that would potentially lead to this issue?  Could you also add `-l debug` to your `inspec exec` command so we can hopefully capture additional information that could help us isolate this issue?

Thanks!

**Comment by adamleff** [comment] 2017-09-05 22:36
Closing due to lack of follow-up. We'll be happy to reopen if needed. Thank you!

**Closed as completed by adamleff** 2017-09-05 22:36 UTC
