### ISSUE TITLE
Transport error while trying to ssh to mac osx 

### ISSUE THREAD

**Issue by Cashwini** [inspec/inspec#788] opened 2016-06-10 20:44 UTC
### Description

Execution of inspec for mac osx fails with transport error
### InSpec and Platform Version

InSpec version 0.23
### Replication Case

Run **_inspec exec -t ssh://username@macip -i password_**

**Comment by chris-rock** [comment] 2016-06-14 01:22
@Cashwini do you use the mac ssh server or another one from brew and co?

**Comment by Cashwini** [comment] 2016-06-14 18:17
I use mac ssh server. I have the same problem when I try to scan mac node from Chef compliance server

**Comment by chris-rock** [comment] 2016-06-15 22:11
I can confirm the issue, this requires a fix in train. The reason is the missing `keyboard-interactive` ssh auth method.

**Comment by chris-rock** [comment] 2016-06-16 09:48
This is fixed via https://github.com/chef/train/issues/111. It will be available in InSpec 0.24

**Closed as completed by chris-rock** 2016-06-16 09:48 UTC
Labels: Type: Bug
