### ISSUE TITLE
Bug: InSpec returns diff test results when var is reassigned

### ISSUE THREAD

**Issue by dialex** [inspec/inspec#2282] opened 2017-11-03 12:42 UTC
### Description

The `describe` and `subject` syntaxes produce different test results when reusing a Ruby variable. The test code below should make it clear.

### InSpec and Platform Version

InSpec ~~v1.42.3~~ 1.43.8 on Ubuntu (Docker)

### Replication Case

```
control "InSpec" do
  title "should should run code top to bottom"
  impact 1.0
  tag 'bug'

  cmd_under_test = "echo Value1"

  describe bash(cmd_under_test) do
    its('stdout') { should match "Value1" }
  end

  describe "Command execution" do
    subject { bash(cmd_under_test) }
    it "should include Value1" do
      expect(subject.stdout).to include 'Value1'
    end
  end

  describe "Command execution" do
    subject { bash(cmd_under_test) }
    it "should match Value1" do
      expect(subject.stdout).to match 'Value1'
    end
  end

  cmd_under_test = "echo Value2"

  describe bash(cmd_under_test) do
    its('stdout') { should match "Value2" }
  end

  describe "Command execution" do
    subject { bash(cmd_under_test) }
    it "should include Value2" do
      expect(subject.stdout).to include 'Value2'
    end
  end

  describe "Command execution" do
    subject { bash(cmd_under_test) }
    it "should match Value2" do
      expect(subject.stdout).to match 'Value2'
    end
  end
end
```

### Results

Expected: all pass.
Actual:

```
  ×  InSpec: should should run code top to bottom (2 failed)
     ✔  Bash command echo Value1 stdout should match "Value1"
     ×  Command execution should include Value1
     expected "Value2\n" to include "Value1"
     Diff:
     @@ -1,2 +1,2 @@
     -Value1
     +Value2

     ×  Command execution should match Value1
     expected "Value2\n" to match "Value1"
     Diff:
     @@ -1,2 +1,2 @@
     -Value1
     +Value2

     ✔  Bash command echo Value2 stdout should match "Value2"
     ✔  Command execution should include Value2
     ✔  Command execution should match Value2
```

**Comment by adamleff** [comment] 2017-11-03 13:22
@dialex this is actually not an issue with InSpec but rather how RSpec operates, and it is expected behavior.

Essentially, an RSpec run has two phases - the phase where all the tests are read in (or "compiled," for lack of a better term), and then the phase where the tests are actually executed. When you place the resource in the `describe` block, any variable used in that argument are evaluated during the "compile" time. When you use a `subject` block, that is lazily loaded at test execution time, only when it's needed. In general, you will get unexpected behavior if you use a compile-time variable (like your local `cmd_under_test` variable) in a lazy-loaded block, especially if you reassign a value.

This is why RSpec has the `let` method that allows variables to be set and lazy-loaded when needed. But this is considerably outside the scope of InSpec. This is also another reason why we do not advocate for using the `expect` syntax with `subject` but rather the `it/should` syntax because it avoids issues like this and avoids the need to understand RSpec itself. 🙂 

If you can provide a more concrete example of what you're trying to accomplish, I'd be more than happy to try and help you personally. Feel free to hit me up at `@adamleff` on the Chef Community Slack or reply to this issue with what you're trying to do. However, because this is not a bug, I will be closing this issue now.

Thanks for writing in. 🙂

**Closed as completed by adamleff** 2017-11-03 13:22 UTC

**Comment by dialex** [comment] 2017-11-03 13:48
I sure wish/hope you have an awesome karma in your life, because you always reply to my issues blazingly fast and packed with information. My hat's off to you sir 😁 🎩 

It's alright, I understand now. It was weird and frustrating for a bit, but when I found what was causing it, it was only a matter of using two variables instead of reusing the same.

Have an awesome day 👍

**Comment by adamleff** [comment] 2017-11-03 14:23
I appreciate the kind words - thank you! 😃
