### ISSUE TITLE
Processes are evaluated at instantiation instead of query time

### ISSUE THREAD

**Issue by absheri** [inspec/inspec#2862] opened 2018-03-22 01:05 UTC
### 🎛 Description

**Choose one:** is this a 🐛 bug report

The processes resource is evaluated at instantiation instead of query time. 

### 🤔 Replication Case

The following test will fail every time:

describe command("COMMAND TO START PROCESS_X") do
  its(:exit_status) { should eq 0}
end

describe processes(PROCESS_X) do
  it { should exist }
end

### 💁 Possible Solutions

In the initialization method for the Processes class there is a call to ``ps_axo`` so that it can build its ``@list``. The calls to build this list should be moved so that it is evaluated when the status is queried.

**Comment by clintoncwolfe** [comment] 2018-03-22 16:51
That *may* be intended behavior.  InSpec is not intended to be a tool for modifying state. `command` is provided as a way to run arbitrary commands to examine the system.  Using it to start a process, then checking to see if that process is running, sounds more like it should be done by a combination of Chef and InSpec.

There is also some thought that the InSpec run should represent a "point in time", and so control order is not gaurenteed.

@chris-rock , @arlimus , @jquick , thoughts?

**Comment by aaronlippold** [comment] 2018-03-24 17:11
Agree with above @clintoncwolfe, this should be the behavior as the validation tool cannot 'break the 4th wall' and be a trusted validator. If it manipulates the system it is evaluating it would break the chain of trust. As with all technology, there are ways around it - `command` - but the above approach is not the right abstraction. @clintoncwolfe is right, the above example, should be a 'joint effort' between your CM toolchain - responsible for setting the state of the system - and your validation chain inspecting that state.

**Comment by clintoncwolfe** [comment] 2018-04-07 22:53
Closing this, as it is intended behavior.  Please feel free to re-open if you'd like to continue the discussion.

**Closed as completed by clintoncwolfe** 2018-04-07 22:53 UTC
