### ISSUE TITLE
'processes' partial matches the first process in canonical order

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#1867] opened 2017-05-30 18:07 UTC
### Description

I'm trying to check the state of a process, but InSpec is picking the wrong process to inspect (because specinfra decided to use `ps -C` (facepalm)).

```
[vagrant@default-centos-7-chef-12-kitchen ~]$ ps -ef |grep haproxy
root     15349     1  0 17:40 ?        00:00:00 /opt/chef/embedded/bin/ruby /opt/chef/embedded/bin/multibinder-haproxy-wrapper /usr/sbin/haproxy -Ds -f /etc/haproxy/conf.d/foo.cfg.erb -p /var/run/haproxy-foo.pid
haproxy  15355 15349  0 17:40 ?        00:00:00 /usr/sbin/haproxy-master
haproxy  15366 15355  0 17:40 ?        00:00:00 /usr/sbin/haproxy -Ds -f /etc/haproxy/conf.d/foo.cfg -p /var/run/haproxy-foo.pid
vagrant  27041 25782  0 18:04 pts/0    00:00:00 grep --color=auto haproxy

  ∅  default: System Package haproxy should be installed; System Package h... (2 failed)
     ✔  System Package haproxy should be installed
     ✔  System Package haproxy version should eq "1.7.2-1.el7"
     ×  Processes haproxy should be running
     undefined method `running?' for Processes haproxy:#<Class:0x007fdd9cc626c8>
     ×  Processes haproxy users should eq "haproxy"

     expected: "haproxy"
          got: ["root", "haproxy"]
```

### InSpec and Platform Version

```
Chef Development Kit Version: 1.4.3
chef-client version: 12.19.36
delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```
Tell us which version of InSpec (`inspec version` or SHA of a commit) and Operating System distribution you are using

### Replication Case

run multiple process that share a common string in their name, try to match a process that does not appear first when you `ps -ef | grep substr`

### Possible Solutions

i can use a `command` matcher with pgrep or whatever, but this is definitely not the ideal behavior.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by adamleff** [comment] 2017-06-02 16:30
@kplimack can you please provide the actual InSpec control that generated this output so we can more easily reproduce this issue? Thanks.

**Comment by miah** [comment] 2019-06-05 22:12
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Closed as completed by miah** 2019-06-05 22:12 UTC
