### ISSUE TITLE
Inspec exec output not sending [DEPRECATION] messages to stderr

### ISSUE THREAD

**Issue by anweiss** [inspec/inspec#1776] opened 2017-05-05 17:30 UTC
### Description

When executing an `inspec exec PATH` against a profile with deprecated functionality, [DEPRECATION] messages aren't sending to stderr and instead being included with stdout.

### InSpec and Platform Version

1.23.0

### Replication Case

`inspec exec PATH`

**Comment by adamleff** [comment] 2017-05-05 17:40
@anweiss thanks for submitting your issue!

I am unable to reproduce this. I think there may be confusion that stderr and stdout are output to your display by default. You need to either redirect stderr to /dev/null or redirect stdout to a file. Either one of these will separate stdout from stderr.

Here's how I was able to confirm this:

 * created a new profile and used deprecated functionality from the `passwd` resource:

```ruby
control 'dep-1' do
  title 'a deprecation test'
  desc 'a deprecation test'
  impact 1.0
  describe passwd do
    its('usernames.length') { should be > 0 }
  end
end
```
 * Ran `inspec exec . --format junit` and confirmed the deprecations at the top:

```
$ inspec exec . --format junit
[DEPRECATION] `passwd.usernames` is deprecated. Please use `passwd.users` instead. It will be removed in version 1.0.0.
<?xml version='1.0'?>
<testsuites>
... etc ...
```

 * redirected stderr to /dev/null with `inspec exec . --format junit 2>/dev/null`:

```
$ inspec exec . --format junit 2>/dev/null
<?xml version='1.0'?>
<testsuites>
...
```

... notice that the deprecation warning is gone from the output.

You could also redirect stdout to a file instead. By default, the `>` redirect operator only redirects stdout:

```
$ inspec exec . --format junit > /tmp/junit.xml
[DEPRECATION] `passwd.usernames` is deprecated. Please use `passwd.users` instead. It will be removed in version 1.0.0.
$ cat /tmp/junit.xml
<?xml version='1.0'?>
<testsuites>
...
```

Can you confirm this behavior on your side, please? If you're still receiving deprecation warnings in stdout, please let us know the deprecated feature being used and a profile sample so we can further troubleshoot.

**Comment by anweiss** [comment] 2017-05-05 17:50
Thanks @adamleff. Indeed the issue was on my end as I was running within a Docker container. When I run it as follows, the [DEPRECATION] methods aren't shown:

```sh
docker run -it --rm --entrypoint '' chef/inspec bash -c "inspec exec <profile> --format=junit 2>/dev/null"
```

**Comment by adamleff** [comment] 2017-05-05 18:04
@anweiss sounds like you're squared away! I'm going to close this issue now, but do let us know if you run into problems and I'll be happy to reopen it.

**Closed as completed by adamleff** 2017-05-05 18:04 UTC
