### ISSUE TITLE
'junit2' is not a valid reporter type. (NotImplementedError)

### ISSUE THREAD

**Issue by jazaval** [inspec/inspec#5243] opened 2020-09-05 00:47 UTC
Attempting to use the new junit2 reporter introduced in InSpec 4.22.2 returns the error:
```
'junit2' is not a valid reporter type. (NotImplementedError)
```

# Describe the problem
Observed on local VM:
```
❯❯❯ inspec exec -t ssh://vagrant:vagrant@vm.local ./test/integration/default/ --reporter junit2                                      
Traceback (most recent call last):
        16: from /opt/chef-workstation/bin/inspec:354:in `<main>'
        15: from /opt/chef-workstation/bin/inspec:354:in `load'
        14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.22.22/bin/inspec:11:in `<top (required)>'
        13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/base_cli.rb:35:in `start'
        12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/cli.rb:272:in `exec'
         7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/base_cli.rb:256:in `config'
         6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/base_cli.rb:256:in `new'
         5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/config.rb:65:in `initialize'
         4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/config.rb:435:in `finalize_options'
         3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/config.rb:479:in `finalize_parse_reporters'
         2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/config.rb:359:in `validate_reporters!'
         1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/config.rb:359:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.22.22/lib/inspec/config.rb:360:in `block in validate_reporters!': 'junit2' is not a valid reporter type. (NotImplementedError)
```
I discovered this issue when Kitchen CI runs started failing to use the `junit` reporter after updating to InSpec 4.22.22. Example kitchen.yml verifier section as follows:
```
verifier:
  name: inspec
  reporter:
    - cli
    - junit:/tmp/%{suite}-%{platform}-inspec.xml
  inspec_tests:
    - test/integration/default
```
I tried updating the `junit` to `junit2` in the kitchen yml, but neither reporter appears to be valid in Kitchen:
```
-----> Starting Test Kitchen (v2.6.0)
-----> Verifying <finder-prefs-catalina>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: ['junit' is not a valid reporter type.] on finder-prefs-catalina
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
```
-----> Starting Test Kitchen (v2.6.0)
-----> Verifying <finder-prefs-catalina>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: ['junit2' is not a valid reporter type.] on finder-prefs-catalina
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
However, the `--reporter junit` option does still work via InSpec CLI for me. Please let me know if I should file this with the test-kitchen repo instead. I'm guessing this has something to do with the changes in #5084 / #5085.

**Comment by jazaval** [comment] 2020-09-05 01:41
@clintoncwolfe with the new class inheritance structure for the `junit` plugin, do you know if I should need to update my kitchen reporter section to `junit2`?

**Comment by Schwad** [comment] 2020-09-08 08:19
@jazaval - you caught an oversight here that we are jumping on remediating immediately and will let the community know as well. Thank you.

`junit2` was merged into the `junit` branch but not formally merged into master. A merge to get this into master and the next imminent release is building here: https://github.com/inspec/inspec/pull/5244

If there's no objection from @clintoncwolfe I will let that pass, look at merge conflicts and get it merged. Thanks!

**Comment by wyardley** [comment] 2020-09-18 19:46
I also can't seem to use inspec-reporter-junit with 4.23.4 (I think it should still exist here since it wasn't moved to a separate plugin til here: https://github.com/inspec/inspec/commit/98ae89e6cc747c2b749eb0e761cdc20e1aeb212b)?

attempting to do something like
```yaml
verifier:
  name: terraform
  systems:
    - name: remote-gcp
      backend: gcp
      reporter:
        - cli
        - junit:junit_remote_gcp.xml
```
(doesn't work with either `junit` or `junit2` with inspec 4.23.4

**Comment by Schwad** [comment] 2020-09-21 08:53
@wyardley this is a known regression that we're fixing in #5244 and will get that moved forward and in a release ASAP. We may also communicate this to the community as a "known issue" against versions.

**Comment by clintoncwolfe** [comment] 2020-09-21 14:41
The kitchen-inspec release 2.2.1 contains a fix for the the junit reporter issue (PR 261, load plugins early). If you're able to upgrade your kitchen-inspec gem separately, that's one fix; alternatively the next release of Chef Workstation will include the fix. Mind you, that refers to the fix for @wyardley's reported issue of the junit (not junit2) reporter failing under Test Kitchen, not the OP issue of junit2 failing to load.

**Comment by james-stocks** [comment] 2020-09-22 15:45
Fixed by https://github.com/inspec/inspec/pull/5244 - we'll release this once it's made it through CI

**Closed as completed by james-stocks** 2020-09-22 15:45 UTC
