### ISSUE TITLE
Conversion Error with JSON Reporter

### ISSUE THREAD

**Issue by djhaynes** [inspec/inspec#3815] opened 2019-02-14 22:49 UTC
Similar to https://github.com/inspec/inspec/issues/3375, we are seeing an Encoding::UndefinedConversionError with the JSON reporter.

.../inspec/reporters/json.rb:8:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

**Comment by jerryaldrichiii** [comment] 2019-02-19 05:06
This is likely a bad character in the output of a resource which is making it into the report, could you provide steps for us to replicate this issue? Without that we don't have much to work on.

The command listed here may help: https://github.com/inspec/inspec/issues/3375#issuecomment-419882128

**Comment by jvogt** [comment] 2019-03-08 15:36
I encountered this issue with the following run locally on my mac:
```
inspec exec compliance://admin/cis-appleosx10.11-level1 --json-config ~/.inspec/config.json # (config.json is setup to report to automate)
...
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/inspec-3.6.6/lib/inspec/reporters/automate.rb:45:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

**Comment by jvogt** [comment] 2019-03-08 15:55
And after some debugging, its coming from a failed control's diff of the expected vs actual stdout of `pwpolicy -getaccountpolicies` for the macos CIS control `xccdf_org.cisecurity.benchmarks_rule_5.2.4_Complex_passwords_must_contain_a_Numeric_Character`

So would resolution be to not use ASCII when capturing stdout?  Or is this a localized OS setting that the end user is responsible to maintain?

**Comment by jvogt** [comment] 2019-03-08 16:08
And FWIW, I'm not proposing this as the solution, but it validates the original source of the bad encoding.

The issue is resolved by changing

```
    def stdout
      result.stdout
    end
```
to
```
    def stdout
      result.stdout.force_encoding(Encoding::UTF_8)
    end
```
inside https://github.com/inspec/inspec/blob/706493f2f386a2cb3a23dcedcee7c30e4281704e/lib/resources/command.rb#L48

**Comment by jerryaldrichiii** [comment] 2019-03-11 16:24
FWIW, I think we should fix this higher up...but `result.stdout.force_encoding(Encoding::UTF_8)` would solve the bulk of issues. I don't see the harm of making that change.

**Comment by zenspider** [comment] 2019-10-09 22:31
I'm not sure but I thought I hit and fixed this...

**Comment by zenspider** [comment] 2019-10-09 22:32
Yup. Fixed this.

**Closed as completed by zenspider** 2019-10-09 22:32 UTC
Labels: Type: Bug, Component: Reporters, Aspect: Portability
