### ISSUE TITLE
Bootstrapping a Node!!!

### ISSUE THREAD

**Issue by murashid786** [inspec/inspec#2534] opened 2018-02-06 22:44 UTC
I am trying to bootstrap a node (centos 7 machine) with chef server and getting multiple issues:

1) Following is my environment info...
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13

2) knife bootstrap ip-00-000-000-171 -x centos -i ~/key-chef1.pem --bootstrap-proxy http://00.00.000.00:80 -N dummyNode
[centos@ip-00-000-000-000 .chef]$ knife bootstrap ip-00-000-000-000 -x centos -i key-chef1.pem --bootstrap-proxy http://00.00.000.00:80 -N testnode1
ERROR: Service temporarily unavailable
/opt/chefdk/embedded/lib/ruby/2.4.0/net/http/response.rb:333:in `stream_check': undefined method `closed?' for nil:NilClass (NoMethodError)
        from /opt/chefdk/embedded/lib/ruby/2.4.0/net/http/response.rb:202:in `read_body'
        from /opt/chefdk/embedded/lib/ruby/2.4.0/net/http/response.rb:229:in `body'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:540:in `rescue in format_rest_error'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:538:in `format_rest_error'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:509:in `humanize_http_exception'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:455:in `humanize_exception'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:446:in `rescue in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:436:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:255:in `load'
        from /opt/chefdk/bin/knife:255:in `<main>'

**Comment by cheeseplus** [comment] 2018-02-06 23:45
This isn't remote related to inspec and the issue is that the bootstrap proxy is returning an error. Best to join up in [Chef Community slack](https://community-slack.chef.io/) for asking questions. As this isn't a relevant issue, closing.

**Closed as completed by cheeseplus** 2018-02-06 23:45 UTC
