### ISSUE TITLE
freebsd service from /usr/local/etc/rc.d is not detected

### ISSUE THREAD

**Issue by svanzoest** [inspec/inspec#1732] opened 2017-04-27 21:22 UTC
### Description

The apache2 cookbook installs the `apache24` package which deploys scripts in `/usr/local/etc/rc.d/` to install and enable a service. This location for rc scripts does not seem to be supported by inspec. See https://github.com/sous-chefs/apache2/issues/477

### InSpec and Platform Version

ChefDK 1.3.40 against FreeBSD 10.3
- kitchen-inspec-0.17.0 
- inspec-1.19.1

### Replication Case

First address sous-chefs/apache2#475 then
run `kitchen test default-freebsd-103` for https://github.com/sous-chefs/apache2

### Actual Result:

the package is installed and running, however, inspec is unable to detect this:
```
$ pkg info |grep apache24
apache24-2.4.25_1              Version 2.4.x of Apache web server
$ service -e |grep apache24
/usr/local/etc/rc.d/apache24
$ service apache24 status
apache24 is running as pid 1413.
$ grep apache24 /etc/rc*
/etc/rc.conf:apache24_enable="YES"
$ grep apache24 /etc/defaults/rc.conf
$
```
Based on https://github.com/chef/inspec/pull/24 it seems like inspec expects an  entry in `/etc/defaults/rc.conf` which does not exist. It seems like it uses `local_startup="/usr/local/etc/rc.d"` to find the init script.
 
 inspec returns the following
```
  apache2::default package
     ∅  apache24 is installed
     expected that `System Package apache24` is installed
     ∅  apache24 is enabled and running
     expected that `Service apache24` is enabled
```

### Possible Solutions

I don't have any experience with FreeBSDs new pkgng or services, but It seems like it is not required to have an entry in `/etc/default/rc.conf` assuming the init script exists in `/usr/local/etc/rc.d/`

**Comment by chris-rock** [comment] 2017-08-27 18:44
I installed `apache24` on a fresh freebsd installation and tested with:
```
describe service("apache24") do 
  it { should be_running }
  it { should be_enabled }
end
```
and got the following result:
```
inspec exec bsdtest.rb -t ssh://vagrant@127.0.0.1:2200 -i /Users/chartmann/Development/tests/freebsd-11/.vagrant/machines/default/virtualbox/private_key
Profile: tests from bsdtest.rb
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2200


  Service apache24
     ↺  The `service` resource is not supported on your OS yet.

Test Summary: 0 successful, 0 failures, 1 skipped

```
By setting https://github.com/chef/inspec/blob/master/lib/resources/service.rb#L150 to `elsif %w{freebsd}.include?(platform.downcase)`, I get the following result:
```
Profile: tests from bsdtest.rb
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2200


  Service apache24
     ✔  should be running
     ✔  should be enabled

Test Summary: 2 successful, 0 failures, 0 skipped
```
Therefore the issue is not in inspec or the service resource. The real problem is in train, extracting the platform name wrongly. This issue is tracked in https://github.com/chef/train/issues/191

**Comment by adamleff** [comment] 2017-10-06 21:58
Closing since it's tracked in the train repo.

**Closed as completed by adamleff** 2017-10-06 21:58 UTC
Labels: Type: Bug
