### ISSUE TITLE
Resource packs should be able to require gems

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4006] opened 2019-05-01 00:41 UTC
If a custom resource requires an additional ruby gem installed there is no way to signal that to InSpec. With the plugin system we could install additional gems specified by the resource pack profile.

Consider a `required_gems` field in the profile that specifies an array of gems the custom resources require.

There should also be a configuration option, and command line flag that prevents installing gems through profiles.

`inspec check` should notify users that additional gems need to installed.

There should be additional logging or auditing capability with details about changes made by the gem installation.

**Comment by btm** [comment] 2019-07-03 04:11
I think this is a duplicate of #3637?

**Comment by clintoncwolfe** [comment] 2019-07-03 19:40
I agree, closing as a duplicate

**Closed as completed by clintoncwolfe** 2019-07-03 19:40 UTC
Labels: Component: Loader, Aspect: Integration
