### ISSUE TITLE
Inspec exec winrm doesn't work from RHEL 7 machine to windows machine

### ISSUE THREAD

**Issue by orabudi** [inspec/inspec#5505] opened 2021-05-05 08:44 UTC
### 🎛 Description
I am trying to run inspec winrm from a RHEL 7 server to try and connect to windows server with the following CLI command:
`inspec exec SOME_BASELINE --host==WINDOWS_HOSTNAME --user=DOMAIN_USER --password=USER_PASSWORD --backend==winrm --reporter==json --chef_license accept`

It shows the following error:

`raise_if_wsman_fault: [WSMAN ERROR CODE: 2] <f:WSManFault Code='2' Machine='MACHINE_HOSTNAME' xmlns:f='http://schemas.microsoft.com/webm/wsman/1/wsmanfault'><f:Message> The WSMan service could not launch a host process to process the given request. Make sure the WSMan provider host server and proxy are properlyy registered. </f:Message></f:WSManFault> (winRM::winRMWSManFault)` 

The linux server is located outside of the domain and the windows server is in the domain. When running the same command from a windows server inside the same domain, with winrm to the other windows server, the command works fine. 

Is there a way to make the inspec exec work in the linux server?

### 🌍 InSpec and Platform Version
inspec version 4.23.11
RHEL 7.9

**Comment by Vasu1105** [comment] 2021-05-05 10:55
I haven't tried from RHEL but from Ubuntu `inspec exec <profile> --host <hostname> --user vasundhara@<domain> --password 'xxxxxx' --backend winrm --reporter json --chef_license accept` this is working for me.

**Comment by Vasu1105** [comment] 2021-05-05 11:05
Also looking at the error it looks like some of the settings missing for winrm communication from outside of the domain this article might help you https://stackoverflow.com/questions/8748173/powershell-remoting-win2008r2-the-wsman-service-could-not-launch-a-host-process

**Comment by Vasu1105** [comment] 2021-05-05 11:27
Checked on REHL7 too this is working properly on that too.

**Comment by orabudi** [comment] 2021-05-05 12:15
hi @Vasu1105 ,
in your second comment in the stackoverflow answer it says to add the machine to the TrustedHosts of the machine running the inspec exec.
 
do you know what the equivalent of that is in the linux machine or if it's even possible to add machines to TrustedHosts in a linux machine? 

thank you

**Comment by Vasu1105** [comment] 2021-05-12 10:08
Closing this issue as not able to reproduce this and doesn't look to be InSpec issue.

**Closed as completed by Vasu1105** 2021-05-12 10:08 UTC
