### ISSUE TITLE
WARN: Unresolved specs

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#1085] opened 2016-09-16 11:24 UTC
### Description

InSpec output started showing specs warning. I think they bring more noise than value:

```
$ inspec exec .
WARN: Unresolved specs during Gem::Specification.reset:
      rspec (~> 3)
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      multi_json (~> 1.10)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

Profile: Basic MySQL (mysql)
Version: 1.1.0
Target:  local://

  ○  mysql-conf-0: Make sure MySQL is installed from an OS supported package

Summary: 0 successful, 0 failures, 1 skipped
```

```
$ inspec exec . --format json-min
WARN: Unresolved specs during Gem::Specification.reset:
      rspec (~> 3)
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      multi_json (~> 1.10)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
{"version":"0.35.0","controls":[{"id":"mysql-conf-0", ...
```
### InSpec and Platform Version

```
[root@ap-cc6 ~]# cat /etc/redhat-release
CentOS release 6.6 (Final)

[root@ap-cc6 ~]# /opt/chef-compliance/embedded/bin/inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      mixlib-shellout (~> 2.0)
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      ffi (>= 1.0.1)
      multi_json (~> 1.10)
      rspec (~> 3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
0.33.2
```

```
$ uname
Darwin

$ inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      rspec (~> 3)
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      winrm (~> 2.0)
      multi_json (~> 1.10)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
0.35.0
```

**Comment by alexpop** [comment] 2016-09-21 12:52
It looks like multiple versions of the gems trigger the WARN messages:

```
[root@ap-cc6 ~]# /opt/chef-compliance/embedded/bin/inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
      ffi (>= 1.0.1)
      multi_json (~> 1.10)
      rspec (~> 3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
0.35.0

[root@ap-cc6 ~]# /opt/chef-compliance/embedded/bin/gem list multi_json
*** LOCAL GEMS ***
multi_json (1.12.1, 1.11.2)

[root@ap-cc6 ~]# /opt/chef-compliance/embedded/bin/gem cleanup net-ssh ffi multi_json rspec
Cleaning up installed gems...
Attempting to uninstall rspec-3.4.0
Successfully uninstalled rspec-3.4.0
Attempting to uninstall ffi-1.9.10
Successfully uninstalled ffi-1.9.10
Attempting to uninstall multi_json-1.11.2
Successfully uninstalled multi_json-1.11.2
Attempting to uninstall net-ssh-3.1.1
Successfully uninstalled net-ssh-3.1.1
Clean Up Complete

[root@ap-cc6 ~]# /opt/chef-compliance/embedded/bin/gem list multi_json
*** LOCAL GEMS ***
multi_json (1.12.1)

[root@ap-cc6 ~]# /opt/chef-compliance/embedded/bin/inspec version
0.35.0
```

**Comment by mrx88** [comment] 2016-09-26 20:48
fyi, i've had similar issue:

$ inspec version
WARN: Unresolved specs during Gem::Specification.reset:
      net-ssh (< 4.0, >= 2.6.5, >= 2.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
1.0.0

$ gem list --local | grep net-ssh
net-ssh (3.2.0, 3.1.1, 2.9.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)

after removing
1. net-ssh-2.9.2
2. net-ssh-3.1.1
   the error disappeared.

**Comment by Constantin07** [comment] 2018-01-24 14:22
Having the same issue, is there a way to turn off this message ?

**Comment by adamleff** [comment] 2018-01-24 15:54
This is not seen in recent versions of InSpec's omnibus package (which is downloadable from downloads.chef.io) or the Docker image published at `chef/inspec`

If you have a way to reproduce this problem, please open a new issue with details. I'm going to close this issue since it duplicates prior similar issues and all known instances of this problem have since been resolved.

**Closed as completed by adamleff** 2018-01-24 15:54 UTC
Labels: Type: Bug
