### ISSUE TITLE
Error running inspec CLI with --input-file option

### ISSUE THREAD

**Issue by manikann** [inspec/inspec#3991] opened 2019-04-28 04:52 UTC
Error running inspec CLI with `--input-files` option

#### InSpec and Platform Version

I tried with 3.9.3 as well as 4.1.4.preview

#### Replication Case

`bundle exec inspec exec --no-backend-cache --no-create-lockfile --input-file=input.yml zonal_private_cluster`

#### Possible workaround for now

Change the position of --input-file option to be the first one

`bundle exec inspec exec --input-file=input.yml --no-backend-cache --no-create-lockfile  zonal_private_cluster`

#### Stacktrace

```
bundle exec inspec exec --no-backend-cache` --no-create-lockfile --input-file=input.yml zonal_private_cluster

Cannot find parser for inputs file 'zonal_private_cluster'. Check to make sure file has the appropriate extension.
```

**Comment by clintoncwolfe** [comment] 2019-04-29 18:10
I think this is a special case of #3558. We do also mangle the array processing, so that may make this worse. Anyway, a fix for this would be based on a fix for #3558.

**Comment by clintoncwolfe** [comment] 2019-12-02 19:33
Est 1 for spike

**Comment by clintoncwolfe** [comment] 2019-12-03 20:02
Upon further reading of the OP's issue, I think this is behaving as intended, though perhaps the message could be more friendly.

From the usage help, `inspec exec help`:

```
     [--input-file=one two three]                       # Load one or more input files, a YAML file with values for the profile to use
```

So `--input-file=input.yml zonal_private_cluster` will be interpreted as an attempt to load two input files, and it fails to parse the second, and gives you a message to that effect. Re-arranging the args to clearly separate the input files from the profile solves the problem, as you found.

**Closed as completed by clintoncwolfe** 2019-12-03 20:02 UTC
Labels: Type: Bug, Priority: High, Aspect: UI-UX, Component: CLI: exec
